loft-sh/vcluster-docs

docs/vcluster/vcluster-yaml/export-kube-config.mdx

added the permissions for exportkubeconfig with different ns

---

package-lock.json
package.json

Reverts loft-sh/vcluster-docs#101

Revert "Upgrade Docusaurus to 3.3 from 3.1"

---

docs/platform/guides/rancher-integration.mdx

DOC-62 Replace vCluster.Pro with Platform

---

docs/vcluster/guides/isolated-control-plane.mdx
docs/vcluster/vcluster-yaml/experimental/isolated-control-plane.mdx

Added guide for configuring isolated control planes using plane helm deployments.

docs(icp): Added Guide for setting up isolated control plane

---

platform/integrations/rancher/rancher-integration.mdx

added example nodeless config

---

platform/integrations/rancher/configuration.mdx

added infos about project id and cluster id

---

platform/installation/air-gapped-installations.mdx
platform/installation/offline-installations.mdx

Closes DOC-2
- adds list of prerequisites needed for air gapped install

DOC-2 | Update air gapped install instructions

---

platform/_partials/vcluster/create-cli.mdx
platform/_partials/vcluster/use-vcluster.mdx

changed manager into driver

---

platform/clusters/advanced/agent-config.mdx

docs: Updated agent config docs

---

platform/install/helm.mdx

Update naming and set explicit version

---

platform/manage/audit.mdx

https://deploy-preview-162--vcluster-docs-site.netlify.app/docs/platform/manage/audit
Resolves DOC-116

Fix audit docs

---

platform/integrations/gitlab-ci.mdx

Change env var names
Update commands to include platform subcommand
Add project specificity
Change space creation example to a tip regarding namespaces.

Gitlab docs update

---

platform/integrations/argocd.mdx

Corrects steps

---

platform/install/gitops.mdx

* s/loft/vcluster-platform/ where appropriate.
* Moves a few things into callouts.
* Makes some lists bulleted rather than csv to stand out.
* Makes some statements more direct, e.g. "should"
* Removes some redundancy in phrasing.

Update ArgoCD docs:

---

vcluster/_partials/deploy/install-beta-cli.mdx

**Issue:**
DOC-102
Install command without flag for chart version does not work with v0.20.0-beta.6.

Update to v0.20.0-beta.9

---

platform/_partials/cluster/connect-ui.mdx
platform/clusters/advanced/ingress-suffix.mdx
platform/clusters/advanced/monitoring.mdx
platform/clusters/cluster-roles.mdx
platform/clusters/connect-cluster.mdx
platform/clusters/what-are-clusters.mdx

Fixes
- DOC-132
- DOC-134
- DOC-136
- DOC-139
- DOC-140

Fixes several platform related doc sections

---

vcluster/configure/vcluster-yaml/policies/README.mdx

Update README.mdx Typo

---

platform/manage/upgrade-platform.mdx

Part of ENG-4065
https://deploy-preview-181--vcluster-docs-site.netlify.app/docs/platform/manage/upgrade-platform

Mention only vcluster CLI is supported for platform upgrade

---

platform/manage/upgrade-platform.mdx

Resolves ENG-3992
https://deploy-preview-178--vcluster-docs-site.netlify.app/docs/platform/manage/upgrade-platform

Add note about how to proceed when the upgrade failed from v3->v4

---

platform/_partials/guides/configure-audit-levels-helm.mdx
platform/_partials/install/upgrade.mdx
platform/install/configure/config.mdx
platform/install/gitops.mdx
platform/install/helm.mdx
platform/install/high-availability.mdx
platform/manage/metrics.mdx

Rename vcluster-control-plane and set explicit version in gitops docs

---

platform/_partials/guides/upgrade-cli.mdx
platform/_partials/install/external-access-nginx-deploy.mdx
platform/_partials/install/set-version.mdx
platform/_partials/install/upgrade-v3-v4.mdx
platform/_partials/install/upgrade.mdx
platform/install/configure/config.mdx
platform/install/gitops.mdx
platform/install/helm.mdx
platform/manage/upgrade-platform.mdx

Update versions throughout platform to reference $PLATFORM_VERSION

---

vcluster/_fragments/non-root-vcluster.mdx

Use correct yaml file

---

vcluster/manage/accessing-vcluster.mdx

Fixes broken link in access & expose docs page

Fix broken link in Access & Expose page

---

platform/virtual-clusters/using-virtual-clusters/retrieve-kube-config.mdx

Use vcluster platform connect

---

platform/integrations/karpenter.mdx

Fixes ENG-4097
Preview: https://deploy-preview-196--vcluster-docs-site.netlify.app/docs/platform/integrations/karpenter

Karpenter Integration Docs

---

vcluster/integrations/enterprise-plugins/plugin.mdx

Reverts loft-sh/vcluster-docs#179

Revert "Eso integration "

---

vcluster/reference/migrations/0-20-migration.mdx

Fixes DOC-210
https://deploy-preview-204--vcluster-docs-site.netlify.app/docs/vcluster/reference/migrations/0-20-migration#eks-distributions

Add EKS migration notes

---

platform/_partials/install/upgrade-v3-v4.mdx

Fix example

---

vcluster/deploy/topologies/high-availability.mdx

Part of ENG-4076
Preview link: https://deploy-preview-211--vcluster-docs-site.netlify.app/docs/vcluster/deploy/topologies/high-availability/#create-the-ha-virtual-cluster

HA with embedded SQLite is not supported

---

_partials/what-is-vcluster-yaml.mdx
docs/get-started.mdx
vcluster/_partials/deploy/deploy-changes.mdx
vcluster/_partials/quick-start-guide/deploy-changes-cli-only.mdx
vcluster/_partials/quick-start-guide/deploy-changes-quick-start-vcluster.mdx
vcluster/_partials/quick-start-guide/deploy-vcluster-with-beta-cli.mdx
vcluster/_partials/quick-start-guide/deploy-vcluster-with-cli.mdx
vcluster/_partials/quick-start-guide/explore-features.mdx
vcluster/_partials/quick-start-guide/key-concepts.mdx
vcluster/_partials/quick-start-guide/pre-requisites.mdx
vcluster/_partials/quick-start-guide/view-host-resources.mdx
vcluster/configure/what-is-vcluster-yaml.mdx
vcluster/deploy/basics.mdx
vcluster/introduction/architecture.mdx
vcluster/introduction/design-principles.mdx
vcluster/quick-start-guide.mdx

Clarify explanations and content

---

platform/namespaces/_partials/namespace/delete-cli.mdx
platform/namespaces/_partials/namespace/import-cli.mdx
platform/namespaces/_partials/namespace/share-cli.mdx

Fixes around platform space

---

vcluster/configure/vcluster-yaml/policies/limit-range.mdx
vcluster/configure/vcluster-yaml/policies/resource-quota.mdx

Fixed yaml snippets in:
- https://deploy-preview-223--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/policies/limit-range
- https://deploy-preview-223--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/policies/resource-quota/

Fixing limitRange and resourceQuota Yaml files

---

vcluster/cli/0-20-cli-changes.mdx
vcluster/cli/_category_.json
vcluster/reference/migrations/loft-cli-vcluster-cli-migration.mdx

https://deploy-preview-233--vcluster-docs-site.netlify.app/docs/vcluster/cli/0-20-cli-changes

v0.20 CLI Changes

---

vcluster/manage/accessing-vcluster.mdx

- Updated example in [Access vCluster Externally](https://www.vcluster.com/docs/vcluster/manage/accessing-vcluster#access-vcluster-externally) as per version 0.20
- Fixed indentation in yaml snippets :
https://www.vcluster.com/docs/vcluster/manage/accessing-vcluster#expose-vcluster

Updated 'Access vCluster Externally' as per vcluster 0.20

---

vcluster/_partials/deploy/deploy-beta.mdx
vcluster/_partials/deploy/deploy.mdx
vcluster/_partials/manage/deploy-changes.mdx
vcluster/_partials/manage/upgrade-version.mdx

Pages changed:
- https://deploy-preview-231--vcluster-docs-site.netlify.app/docs/vcluster/deploy/basics
- https://deploy-preview-231--vcluster-docs-site.netlify.app/docs/vcluster/manage/deploy-changes
- https://deploy-preview-231--vcluster-docs-site.netlify.app/docs/vcluster/manage/upgrade-version

Adding changes for deploying vCluster using CAPI

---

vcluster/configure/vcluster-yaml/README.mdx
vcluster/configure/what-is-vcluster-yaml.mdx
vcluster/reference/migrations/0-20-migration.mdx

Fixes DOC-228
https://deploy-preview-232--vcluster-docs-site.netlify.app/docs/vcluster/configure/what-is-vcluster-yaml#how-do-i-upgrade-my-019x-and-earlier-virtual-cluster-configurations
https://deploy-preview-232--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/#create-a-virtual-cluster-with-a-config-file
https://deploy-preview-232--vcluster-docs-site.netlify.app/docs/vcluster/reference/migrations/0-20-migration

Add more places about converting

---

platform/install/configure/config.mdx

resolves ENG-4224
@matskiv @deniseschannon let me know if you think there's a better place in the docs to put this
@hidalgopl Next time, you can take the deploy preview and add it into comment field so it's easier to review:
https://deploy-preview-251--vcluster-docs-site.netlify.app/docs/platform/install/configure/config#setting-additional-certificate-authority-for-platform

add section about additionalCA

---

vcluster/configure/vcluster-yaml/networking/replicate-services.mdx

add missing networking parent in yaml snippets

Update replicate-services.mdx add networking in yaml snippets

---

hack/vcluster/partials/main.go
vcluster/_fragments/integrations/kube-virt.mdx
vcluster/_partials/config/integrations/kubeVirt.mdx
vcluster/configure/vcluster-yaml/integrations/kubeVirt.mdx
vcluster/integrations/kubevirt/kubevirt.mdx

feat: add kubevirt docs

---

go.mod
go.sum
hack/vcluster/partials/main.go
vcluster/_fragments/eso.mdx
vcluster/_partials/config/integrations.mdx
vcluster/_partials/config/integrations/externalSecrets.mdx
vcluster/configure/vcluster-yaml/integrations/eso.mdx
vcluster/configure/vcluster-yaml/integrations/metricsServer.mdx
vcluster/integrations/external-secrets/_category_.json
vcluster/integrations/external-secrets/guide.mdx
vendor/github.com/blang/semver/.travis.yml
vendor/github.com/blang/semver/LICENSE
vendor/github.com/blang/semver/README.md
vendor/github.com/blang/semver/json.go
vendor/github.com/blang/semver/package.json
vendor/github.com/blang/semver/range.go
vendor/github.com/blang/semver/semver.go
vendor/github.com/blang/semver/sort.go
vendor/github.com/blang/semver/sql.go
vendor/github.com/loft-sh/vcluster-config/config/config.go
vendor/github.com/loft-sh/vcluster-config/config/default_extra_values.go
vendor/github.com/loft-sh/vcluster-config/config/values.yaml
vendor/modules.txt

added guide for eso

---

platform/_partials/auth/sso/oidc.mdx

Added comment to OIDC SSO documentation for Keycloak users

Keycloak Comment

---

vcluster/deploy/security/fips.mdx

Added new doc page: https://deploy-preview-270--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/security/fips

Added FIPS docs

---

vcluster/_fragments/how-does-syncing-work.mdx
vcluster/_fragments/integrations/kube-virt.mdx
vcluster/configure/vcluster-yaml/sync/README.mdx
vcluster/introduction/architecture.mdx

feat: add how does syncing work

---

platform/integrations/rancher/configuration.mdx
platform/integrations/rancher/rancher-integration.mdx

https://deploy-preview-273--vcluster-docs-site.netlify.app/docs/platform/integrations/rancher/configuration
https://deploy-preview-273--vcluster-docs-site.netlify.app/docs/platform/integrations/rancher/rancher-integration

Fixing Rancher integration docs for clarity

---

platform/configure/config.mdx
platform/configure/domain.mdx

This links existing TLS configuration section with additionalCA, so it's clear how to get the value for additionalCA option.

add docs on how to get a value for additionalCA

---

platform/administer/templates/create-namespace-template.mdx
platform/administer/templates/create-virtual-cluster-template.mdx
platform/configure/config.mdx
platform/configure/single-sign-on/providers/github.mdx
platform/configure/single-sign-on/providers/gitlab.mdx
platform/configure/single-sign-on/providers/google.mdx
platform/configure/single-sign-on/providers/ldap.mdx
platform/configure/single-sign-on/providers/microsoft.mdx
platform/configure/single-sign-on/providers/okta.mdx
platform/configure/single-sign-on/providers/openid-connect.mdx
platform/configure/single-sign-on/providers/other-dex.mdx
platform/configure/single-sign-on/providers/saml.mdx
platform/integrations/hashicorp-vault.mdx
platform/integrations/rancher/rancher-integration.mdx
platform/understand/what-are-virtual-clusters.mdx
platform/use-platform/apps/use-on-demand.mdx
platform/use-platform/virtual-clusters/add-virtual-clusters.mdx
platform/use-platform/virtual-clusters/create/create-no-template.mdx
platform/use-platform/virtual-clusters/create/create-with-template.mdx
platform/use-platform/virtual-clusters/key-features/sleep-mode.mdx

fix: change site to relative path in _partials

---

vcluster/configure/vcluster-yaml/sync/to-host/core/pods.mdx
vcluster_versioned_docs/version-0.20.0/configure/vcluster-yaml/sync/to-host/core/pods.mdx

Reference code: https://github.com/loft-sh/vcluster/blob/v0.20.0/pkg/util/toleration/toleration.go
Resolves https://github.com/loft-sh/vcluster/issues/2199

docs: fix `enforceTolerations` docs

---

.github/workflows/reviewdog.yaml
CONTRIBUTING.md
README.md

Reviewdog is a reporting tool that provides ways to post linter warnings and errors as review comments to a PR.
It uses the output of lint tools and posts them as a comment if findings are in the diff of patches to review.

lint: Added reviewdog GitHub action

---

platform/_partials/install/install-next-steps.mdx
platform/install/quick-start-guide.mdx

Closes DOC-271
Docs Link: https://deploy-preview-291--vcluster-docs-site.netlify.app/docs/platform/install/quick-start-guide
> [!NOTE]
> Commits will be squashed before merging, leaving them as they are for easier review

feat: review install using cli (#271)

---

platform/_partials/install/login-after-helm-install.mdx
platform/install/helm.mdx
platform/install/quick-start-guide.mdx

Closes DOC-294
- [Using CLI preview](https://deploy-preview-301--vcluster-docs-site.netlify.app/docs/platform/install/quick-start-guide/)
- [Install vCluster Platform With Helm preview](https://deploy-preview-301--vcluster-docs-site.netlify.app/docs/platform/install/helm)

chore: helm install and cli install cleanup (#294)

---

.github/styles/config/vocabularies/Loft/accept.txt
platform/_partials/install/set-version.mdx
platform/_partials/install/upgrade.mdx
platform/install/advanced/air-gapped.mdx
src/components/Mark/index.js

Closes DOC-276
[Air-Gapped Install Preview](https://deploy-preview-303--vcluster-docs-site.netlify.app/docs/platform/install/advanced/air-gapped)

feat: review airgapped install (#276)

---

platform/configure/config.mdx

Closes DOC-278
[Platform Configuration Preview](https://deploy-preview-304--vcluster-docs-site.netlify.app/docs/platform/configure/config)
> [!IMPORTANT]
> https://github.com/loft-sh/vcluster-docs/pull/303 must be merged first

feat: improve vcluster platform config (#278)

---

platform/_partials/guides/upgrade-cli.mdx
platform/_partials/install/external-access-loadbalancer-apply.mdx
platform/_partials/install/external-access-loadbalancer-aws.mdx
platform/_partials/install/external-access-loadbalancer-get-external-ip.mdx
platform/_partials/install/external-access-loadbalancer-other.mdx
platform/_partials/install/external-access-loadbalancer-validate.mdx
platform/_partials/install/external-access-nginx-deploy.mdx
platform/_partials/install/external-access-nginx-get-external-ip.mdx
platform/_partials/install/external-access-nginx-loft-values.mdx
platform/_partials/install/external-access-nginx-set-a-record.mdx
platform/_partials/install/external-access-nginx-start.mdx
platform/_partials/install/set-version.mdx
platform/configure/domain.mdx

Closes DOC-284
[Custom Domain Preview](https://deploy-preview-306--vcluster-docs-site.netlify.app/docs/platform/configure/domain)
> [!IMPORTANT]
> https://github.com/loft-sh/vcluster-docs/pull/303 must be merged first

feat: review custom domain configuraiton section (#284)

---

.github/workflows/reviewdog.yaml

fix: reviewdog token access

---

platform/install/gitops.mdx

Closes DOC-275
[Docs link preview](https://deploy-preview-292--vcluster-docs-site.netlify.app/docs/platform/install/gitops)
> [!NOTE]
> Commits will be squashed before merging, leaving them as they are for easier review

feat: review install using argocd

---

.github/workflows/reviewdog.yaml

fix: file detection

---

.github/workflows/reviewdog.yaml

This fixes incorrect file detection in the linting action.

fix changed file detection

---

.github/styles/Loft/capitalize-helm-project.yml
.github/styles/Loft/lowecase-helm-command.yml

feat: vale rule enforcing proper capitalization of the word helm

---

platform/configure/high-availability.mdx

Closes DOC-285
[High Availability Preview](https://deploy-preview-308--vcluster-docs-site.netlify.app/docs/platform/configure/high-availability)
> [!IMPORTANT]
> https://github.com/loft-sh/vcluster-docs/pull/303 must be merged first

feat: review high availability configuratuion (#285)

---

.github/styles/config/vocabularies/Loft/accept.txt
platform/_partials/install/base-prerequisites.mdx
platform/_partials/install/list-helm-versions.mdx
platform/install/_category_.json
platform/install/advanced/air-gapped.mdx
platform/install/gitops.mdx
platform/install/helm.mdx
platform/install/quick-start-guide.mdx

feat: standardize menu and improve installation sections content

---

docusaurus.config.js

Closes DOC-310
[Docs Preview](https://deploy-preview-332--vcluster-docs-site.netlify.app/docs/)

chore: disable dark mode (#310)

---

platform/_fragments/cli-steps/connect-platform.mdx
platform/_fragments/cli-steps/platform-add-cluster.mdx
platform/_fragments/cli-steps/platform-connect-cluster.mdx
platform/_fragments/ui-steps/clusters-select.mdx
platform/_partials/vcluster/import-cli.mdx
platform/use-platform/virtual-clusters/add-virtual-clusters.mdx

https://deploy-preview-215--vcluster-docs-site.netlify.app/docs/platform/virtual-clusters/advanced/import-virtual-clusters

Fix importing virtual clusters

---

.github/styles/config/vocabularies/Loft/accept.txt
platform/administer/monitoring/central-hostpath-mapper.mdx
vcluster_versioned_docs/version-0.20.0/configure/vcluster-yaml/control-plane/components/host-path-mapper.mdx

fix deployment instructions and details for the OSS & Central HostPath Mapper

---

src/css/theme.scss.bak

Closes DOC-327
[Docs Preview](https://deploy-preview-341--vcluster-docs-site.netlify.app/docs/platform/install/quick-start-guide/#download-and-install-vcluster-cli)

chore: fix css issues with the tabs

---

src/css/admonitions.scss

Closes DOC-327
[Docs Preview](https://deploy-preview-344--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/database/external)

feat: configuring consistent top and bottom admonitions margins

---

platform/administer/connector/_category_.json
platform/administer/connector/database.mdx
vcluster/configure/vcluster-yaml/control-plane/components/backing-store/database/external.mdx

Preview platform: https://deploy-preview-314--vcluster-docs-site.netlify.app/docs/platform/administer/connector/database
Preview vcluster: https://deploy-preview-314--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/database/external

Add shared database docs

---

docusaurus.config.js

Closes DOC-340
[Platform Menu Preview](https://deploy-preview-349--vcluster-docs-site.netlify.app/docs/platform)

feat: indicate stable platform version on the menu

---

.github/styles/config/vocabularies/Loft/accept.txt

chore: add pro label to vale exceptions

---

docusaurus.config.js

Closes DOC-344
Merge when the [changelog](https://www.vcluster.com/releases/en/changelog?hideLogo=true&hideMenu=true&theme=dark&embed=true&c=vCluster) versions are ready.

feat: update announcement bar for new releases

---

vcluster_versioned_docs/version-0.20.0/configure/vcluster-yaml/control-plane/other/advanced/workload-service-account.mdx
vcluster_versioned_docs/version-0.21.0/configure/vcluster-yaml/control-plane/other/advanced/workload-service-account.mdx

chore: port workload sa changes to new versions

---

docusaurus.config.js

chore: add OSS documentation license

---

platform/administer/templates/advanced/parameters.mdx

chore: add parameter value types

---

docs/_partials/kubeconfig_update.mdx
vcluster/deploy/environment/eks.mdx

Closes DOC-83
[Deploy vCluster on EKS Preview](https://deploy-preview-361--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/eks)

feat: deploying vCluster on EKS

---

.vale.ini

chore: stop vale package sync on each CI run

---

.vale.ini

chore: ignore () part of markdown links in vale

---

platform/configure/config.mdx

Corrected the reference to values.yaml file from vcluster.yaml file.

updated platform config details

---

docs/_partials/kubeconfig_update.mdx
docs/_partials/managed_k8s_install_vcluster.mdx
vcluster/deploy/environment/aks.mdx

Closes DOC-350
[Deploy vCluster on AKS Preview](https://deploy-preview-367--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/aks)

feat: deploy vCluster on AKS

---

vcluster/deploy/environment/eks.mdx

Closes DOC-362
[Deploy vCluster on EKS Preview](https://deploy-preview-377--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/eks)

feat: remove standalone pod identity from EKS

---

platform/configure/cost-control.mdx

Cost Control Dashboard configuration settings (first draft). Documentation for resizing storage will be a separate PR.
<!--Add the Github or Linear ticket reference>
Closes DOC-359

Add cost control dashboard configuration page

---

.github/styles/Google/Headings.yml
.github/styles/Google/WordList.yml
platform/_partials/install/base-prerequisites.mdx
vcluster/_partials/deploy/fips-config.mdx
vcluster/_partials/deploy/license_key.mdx
vcluster/deploy/topologies/air-gapped.mdx

Closes DOC-95
[vCluster Pro air-gapped install Preview](https://deploy-preview-379--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/topologies/air-gapped)

Doc 95/airgapped deploy

---

vcluster/deploy/topologies/air-gapped.mdx

- improve helm install command
- explain and improve the resource limits code
[vCluster Pro air-gapped install Preview](https://deploy-preview-388--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/topologies/air-gapped)
Closes DOC-372

chore: address qa feedback on vCluster airgapped

---

configsrc/vcluster/main/vcluster.schema.json
hack/vcluster/partials/main.go
vcluster/configure/vcluster-yaml/experimental/native-sleep-mode.mdx
vcluster_versioned_docs/version-0.22.0/_partials/config/controlPlane.mdx
vcluster_versioned_docs/version-0.22.0/_partials/config/controlPlane/distro.mdx
vcluster_versioned_docs/version-0.22.0/_partials/config/controlPlane/distro/k8s.mdx
vcluster_versioned_docs/version-0.22.0/_partials/config/experimental.mdx
vcluster_versioned_docs/version-0.22.0/_partials/config/experimental/sleepMode.mdx
vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/experimental/native-sleep-mode.mdx

[Document Preview](https://deploy-preview-401--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/experimental/native-sleep-mode)
<!--Add the Github or Linear ticket reference>
Closes DOC-

SleepMode docs w/pending config reference

---

vcluster/_fragments/integrations/cert-manager.mdx
vcluster_versioned_docs/version-0.22.0/_fragments/integrations/cert-manager.mdx

fix code fence title reference
Closes DOC-381

fix: fix code fence title reference

---

platform/install/supported_versions.mdx
vcluster/deploy/supported_versions.mdx
vcluster_versioned_docs/version-0.22.0/deploy/supported_versions.mdx

Add in supported versions matrix
https://deploy-preview-404--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/supported_versions
https://deploy-preview-404--vcluster-docs-site.netlify.app/docs/platform/install/supported_versions
Closes DOC-1

Add supported versions pages

---

platform/install/gitops.mdx

Update the indentation for YAML examples in [Deploy using ArgoCD](https://www.vcluster.com/docs/platform/install/gitops#cluster-resources)
[Link to preview doc](https://deploy-preview-473--vcluster-docs-site.netlify.app/docs/platform/install/gitops#cluster-resources)
Closes DOC-445

fix: Update YAML indentation

---

.github/styles/Google/WordList.yml

Remove advice around the word "disabled".

chore: Update wordlist for linter

---

vcluster/deploy/environment/eks.mdx

[Create EKS cluster](https://deploy-preview-487--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/eks)
Closes DOC-483

fix: eksctl command needs iam setting

---

docs/_partials/vcluster_supported_versions.mdx

- adds v23 release and maintenance dates.
Closes DOC-468

feat: add `v23` release to support matrix

---

staging/your-doc-name.mdx

Integrating the vCluster binary as a kubectl plugin enables Kubernetes users to manage their vClusters seamlessly via kubectl commands.

vcluster-kubectl-plugin.mdx

---

vcluster/_fragments/sleepmode-deployment-example.mdx
vcluster/_fragments/sleepmode-ingress-example.mdx
vcluster/configure/vcluster-yaml/_code/sleepmode-deployment-config.yaml
vcluster/configure/vcluster-yaml/_code/sleepmode-host-ingress-config.yaml
vcluster/configure/vcluster-yaml/sleep-mode.mdx

[Sleep Mode Preview](https://deploy-preview-507--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sleep-mode)
Closes DOC-496

fix: annotation docs and examples

---

staging/custom_managementroles_in_vclusterplatform.mdx

…vcluster platform
Added Kb article 
Closes DOC-

 feat: add kb article content for adding custom management role for project in platform

---

staging/Resolving etcd NOSPACE Alarm in vCluster.mdx

add kb article content on etcd compaction

---

docs/_partials/vcluster_supported_versions.mdx
vcluster/_fragments/distro/compat-k8s.mdx
vcluster/_partials/deploy/distros.mdx
vcluster/deploy/upgrade/supported_versions.mdx

- Update compatibility specs and remove erroneous versioning
- [Link to Matrix Preview](https://deploy-preview-510--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/upgrade/supported_versions)
- [Link to Distro Preview](https://deploy-preview-510--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/distro/k8s)
Closes DOC-484

fix: update table for supported compatibility

---

.github/workflows/create-linear-issue.yaml

fix(ci): linear action version

---

.github/workflows/create-linear-issue.yaml

feat(ci): prepend linear issue title with "follow-up:"

---

platform/how-to/uninstall.mdx

Should be merged after #536 
Closes DOC-

fix: vcluster version for platform uninstall intro

---

vcluster/manage/backup-restore.mdx
vcluster_versioned_docs/version-0.24.0/manage/backup-restore.mdx

0.24 version updates - Clean up snapshot and restore docs

---

vcluster/_fragments/sleepmode-deployment-example.mdx
vcluster/_fragments/sleepmode-ingress-example.mdx
vcluster/configure/vcluster-yaml/sleep-mode.mdx

- Copy edits to align with style guide 
[Link to Preview](https://deploy-preview-544--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sleep-mode)

refactor: update docs for improved readability

---

staging/exposing-vCluster-platform-with-Istio.mdx

Exposing vCluster Platform with Istio
Closes DOC-

kb:Create exposing-vCluster-platform-with-Istio.mdx

---

.github/styles/config/vocabularies/Loft/accept.txt

- Add JavaScript to vale to make it less noisy 
Closes DOC-

fix: add word to list

---

platform/install/gitops.mdx
platform_versioned_docs/version-4.2.0/install/gitops.mdx

- Add manual labels needed for namespace creation
Closes DOC-77

fix: add manual namespace labels

---

.github/styles/config/vocabularies/Loft/accept.txt

- More words to the list
Closes DOC-

Add words to list

---

vcluster/learn-how-to/retrieve-vcluster-config.mdx

- Missing part of the command.
- Raised by @cbron in this [Slack thread](https://loft-labs-inc.slack.com/archives/C058PCKE17W/p1744199346014509?thread_ts=1744157116.140519&cid=C058PCKE17W)
[Link to Preview](https://deploy-preview-599--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/retrieve-vcluster-config)
Closes DOC-

fix: update incomplete command

---

.github/workflows/backport-docs.yml

fix(ci): backport trigger

---

.github/workflows/backport-docs.yml

chore(ci): use v1 version of the backport action

---

docs/_partials/managed_k8s_install_vcluster.mdx
src/components/InterpolatedCodeBlock/index.js
vcluster/deploy/environment/aks.mdx
vcluster/deploy/environment/eks.mdx
vcluster/deploy/environment/gke.mdx

https://deploy-preview-617--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/aks/
https://deploy-preview-617--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/eks/
https://deploy-preview-617--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/gke/
Closes DOC-194

feat: configurable copy paste

---

.github/styles/config/vocabularies/Loft/accept.txt

fix: update vale accept words

---

hack/vcluster/partials/main.go
vcluster/_fragments/integrations/istio.mdx
vcluster/_partials/config/integrations/istio.mdx
vcluster/configure/vcluster-yaml/integrations/istio.mdx
vcluster/integrations/istio.mdx

Docs for istio integration with an example.
[Istio docs preview](https://netlify.preview/docs/xxxx)
Closes DOC-373

Add istio integration docs

---

platform_versioned_docs/version-4.2.0/configure/config.mdx

fix: Platform Agent Link

---

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/README.mdx

https://deploy-preview-651--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/
Closes DOC-

Update backing store page

---

platform/_partials/install/open-ports.mdx
platform/install/gitops.mdx

fix: clarify firewall requirements with generic term

---

.github/styles/config/vocabularies/Loft/accept.txt
CONTRIBUTING.md
docs/_partials/0-20.migration.mdx
docusaurus.config.js
vcluster/configure/vcluster-yaml/telemetry.mdx
vendor/github.com/loft-sh/api/v4/pkg/apis/ui/v1/ui_types.go

Updating this with the Brand Guide

Update Loft Labs to LoftLabs

---

netlify.toml

feat(ui) - redirects for backing store docs link

---

platform/install/upgrade-migrate/lifecycle-policy.mdx

Update lifecycle-policy for 4.2 for next release.mdx

---

platform_versioned_docs/version-4.2.0/install/upgrade-migrate/lifecycle-policy.mdx

Update lifecycle-policy to extend 4.2.mdx

---

platform/install/upgrade-migrate/lifecycle-policy.mdx
vcluster/deploy/upgrade/supported_versions.mdx

- Just update language for EOS and EOL terminology 
Closes DOC-625

fix: EOS and EOL language update

---

docs/_partials/vcluster_supported_versions.mdx
platform_versioned_docs/version-4.2.0/install/upgrade-migrate/lifecycle-policy.mdx

fix: update table

---

docs/_partials/vcluster_supported_versions.mdx

-  Add EOS and EOL  for v25 release
Closes DOC-578

fix: update table for v25 release

---

vcluster/configure/vcluster-yaml/external/platform/api-key.mdx
vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/external/platform/README.mdx
vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/external/platform/api-key.mdx

- Add steps for secret
[Link to Preview](https://deploy-preview-670--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/external/platform/api-key)
Closes DOC-620

fix: add steps for connection

---

vcluster/configure/vcluster-yaml/external/platform/api-key.mdx
vcluster/configure/vcluster-yaml/sync/from-host/nodes.mdx
vcluster/learn-how-to/control-node-ip-visibility.mdx
vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/external/platform/api-key.mdx

Also fixes admonitions indentation in Step tags
https://deploy-preview-698--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/control-node-ip-visibility
Closes DOC-603

feat(vcluster): how to control node IP visibility

---

platform/administer/connector/database.mdx
vcluster/configure/vcluster-yaml/control-plane/components/backing-store/database/external.mdx

feat: add posgres option to database connectors

---

netlify.toml

Added new platform permalink for project secrets.

feat: Add platform permalink for the project secret crd

---

docusaurus.config.js

- Added Changelog link to the main navigation bar
- Changed Website and Blog links to open in new tabs
https://deploy-preview-714--vcluster-docs-site.netlify.app/docs/
Closes DOC-640

feat: add changelog link to navigation and update link behavior

---

vcluster/learn-how-to/capture-pprof-vcluster.mdx

Updated KB article on capturing pprof profile

---

vcluster/configure/vcluster-yaml/external/platform/api-key.mdx
vcluster_versioned_docs/version-0.25.0/configure/vcluster-yaml/external/platform/api-key.mdx

fix: Update apiKey doc

---

platform/configure/domain.mdx

Fixes vCluster yaml used in custom self-signed TLS setup tutorial. 
Part of ENG-6290

Fix self signed TLS setup docs

---

platform/install/environments/aws.mdx

Added a step-by-step guide for setting up the Platform on AWS EKS.
[Document Preview](https://deploy-preview-752--vcluster-docs-site.netlify.app/docs/platform/next/install/environments/aws).
Closes DOC-385

feat: add platform setup on aws

---

docusaurus.config.js

https://deploy-preview-771--vcluster-docs-site.netlify.app/docs/
Closes DOC-695

chore: remove minor version placeholder in platform dropown

---

vcluster/_fragments/private-nodes.mdx

https://deploy-preview-776--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/private-nodes/

Update private-nodes to clarify what it means

---

src/js/details-clicks.js

This is the regression error introduced in #740
Restore copy button functionality by adding targeted event listeners for `DOMContentLoaded`, `hashchange` (sidebar navigation), `visibilitychange` (tab switching), and page change detection using MutationObserver that watches for URL changes during Docusaurus navigation. 
These calls only execute when config fields are present, avoiding the aggressive polling that caused "Too many calls to Location or History APIs" while ensuring copy buttons appear reliably on all config pages.
Closes DOC-703

fix(vcluster): re-enable copy button

---

netlify.toml

Adding new platform redirects for an upcoming feature

feat: Add new docs redirects related to kubernetes distros

---

vcluster/_fragments/private-nodes.mdx

Rework the layout of private nodes based on current information. 
Preview link: https://deploy-preview-806--next-vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/private-nodes/

Rework private nodes layout

---

netlify.toml

feat(ui) - add docs redirect

---

.github/styles/config/vocabularies/Loft/accept.txt
vcluster/_partials/deploy/deploy.mdx
vcluster/configure/vcluster-yaml/README.mdx
vcluster/configure/what-is-vcluster-yaml.mdx

[Link to Preview](https://deploy-preview-816--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/what-is-vcluster-yaml#frequently-asked-questions)
Closes DOC-

refactor: rewrite vCluster YAML def

---

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded.mdx

Resolves ENG-7354
https://deploy-preview-814--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded

feat: embedded etcd

---

docs/_partials/vcluster_supported_versions.mdx
docusaurus.config.js
vcluster/deploy/upgrade/supported_versions.mdx
vcluster_versioned_docs/version-0.20.0/deploy/topologies/multi-namespace-mode.mdx
vcluster_versioned_docs/version-0.23.0/deploy/upgrade/supported_versions.mdx
vcluster_versioned_docs/version-0.24.0/deploy/upgrade/supported_versions.mdx
vcluster_versioned_docs/version-0.25.0/deploy/upgrade/supported_versions.mdx
vcluster_versioned_docs/version-0.26.0/deploy/upgrade/supported_versions.mdx

[Link to Preview](https://deploy-preview-836--vcluster-docs-site.netlify.app/docs/)
Closes DOC-693

fix: Add release banner

---

vcluster/_fragments/private-nodes.mdx

Add sleepmode limitation

---

netlify.toml

Added new platform redirect for the nodes page.

feat: Add platform redirect for nodes page

---

README.md

Adds instructions to README.md for local development.

Add instructions for developing locally

---

platform/understand/ranges-app-template.mdx

fix: incorrect template parameters link

---

.github/styles/config/vocabularies/Loft/accept.txt
vcluster/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.20.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.21.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.23.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.25.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx
vcluster_versioned_docs/version-0.26.0/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots.mdx

https://deploy-preview-913--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/sync/to-host/storage/volume-snapshots
Closes DOC-764

feat(vcluster): improve volume snapshot content config

---

docs/get-started.mdx
vcluster/_partials/quick-start-guide/key-concepts.mdx
vcluster/_partials/quick-start-guide/pre-requisites.mdx
vcluster/introduction/architecture.mdx
vcluster/introduction/what-are-virtual-clusters.mdx
vcluster/quick-start-guide.mdx

General content changes for private nodes

---

vcluster/configure/tenancy-model.mdx
vcluster/manage/accessing-vcluster.mdx
vcluster/manage/backup-restore.mdx
vcluster/manage/certificates.mdx
vcluster/manage/deploy-changes.mdx

Changes around backup and restore and others

---

docusaurus.config.js

- fix image zoom animation on the main page
- fix default links to vCluster and Platform to point to latest versions
https://deploy-preview-985--vcluster-docs-site.netlify.app/docs/
Closes DOC-891

fix(layout): zoom animation and header links

---

vcluster/configure/vcluster-yaml/control-plane/components/coredns.mdx
vcluster/introduction/architecture.mdx
vcluster/introduction/what-are-virtual-clusters.mdx

Move diagrams into shared and dedicated nodes sections

---

vcluster/deploy/worker-nodes/host-nodes/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.20.0/deploy/topologies/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.21.0/deploy/topologies/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.22.0/deploy/topologies/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.23.0/deploy/topologies/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.24.0/deploy/topologies/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.25.0/deploy/topologies/isolated-control-plane.mdx
vcluster_versioned_docs/version-0.26.0/deploy/topologies/isolated-control-plane.mdx

Isolated control plane deprecation notice

---

vcluster/_fragments/patches.mdx

ENG-8212 feature(b64): Add basic JS and additional base64 functions

---

vcluster/deploy/worker-nodes/private-nodes/manage.mdx
vcluster_versioned_docs/version-0.27.0/deploy/worker-nodes/private-nodes/manage.mdx

Fix remove worker node

---

src/theme/DocSidebar/Desktop/Content/index.js

chore: fix eos eol

---

platform/use-platform/namespaces/key-features/isolation.mdx

https://deploy-preview-1026--vcluster-docs-site.netlify.app/docs/platform/next/use-platform/namespaces/key-features/isolation
Closes DOC-688

feat(platform): improve isolated namespaces docs

---

netlify.toml

fix(infra): remove deploy redirects

---

netlify.toml
package.json

fix(infra): fix splat redireciton

---

vcluster/configure/vcluster-yaml/private-nodes/README.mdx
vcluster_versioned_docs/version-0.27.0/configure/vcluster-yaml/private-nodes/README.mdx

feat(vcluster): add private node configuration link

---

platform_versioned_docs/version-4.3.0/install/environments/azure.mdx

https://deploy-preview-1068--vcluster-docs-site.netlify.app/docs/platform/
Closes DOC-916

chore(platform): backport aks install docs

---

CONTRIBUTING.md
platform/install/upgrade-migrate/migrate-to-hostcluster.mdx
platform_versioned_docs/version-4.2.0/install/upgrade-migrate/migrate-to-hostcluster.mdx
platform_versioned_docs/version-4.3.0/install/upgrade-migrate/migrate-to-hostcluster.mdx
vcluster/_fragments/metrics-server.mdx
vcluster/introduction/architecture.mdx

Add the Contribution guide content and fix a broken link.
N/A
N/A

fix: add Contribution guide content and fix broken links

---

.github/workflows/sync-next-branch.yml

fix(ci): correct loft-bot login

---

.github/workflows/sync-next-branch.yml
hack/sync-branches.sh

fix(ci): linter issues and script output

---

.github/workflows/sync-next-branch.yml
hack/sync-branches.sh

fix(ci): use merge instead of rebase

---

.github/workflows/redirect-check.yml
hack/netlify-auth.hurl

feat(ci): verify if we run against next branch with protection

---

platform/use-platform/virtual-clusters/key-features/auto-snapshot.mdx
platform/use-platform/virtual-clusters/key-features/snapshots.mdx

Fix up auto snapshot in platform

---

.github/workflows/redirect-check.yml

1. Run from forks with access to secrets like NETLIFY_SITE_PASSWORD
2. Test the actual PR code from the fork
3. Handle password-protected Netlify previews on the next branch
Closes DOC-
@netlify /docs

feat(ci): run next sync on target branch

---

docs/_partials/vcluster_supported_versions.mdx

Convert support matrix to html and call out EOL

---

vcluster/configure/vcluster-yaml/private-nodes/auto-nodes.mdx
vcluster_versioned_docs/version-0.28.0/configure/vcluster-yaml/private-nodes/auto-nodes.mdx

chore: remove vpn from docs

---

docs/_partials/platform_supported_versions.mdx
docusaurus.config.js
platform/install/upgrade-migrate/lifecycle-policy.mdx
platform_versioned_docs/version-4.2.0/install/upgrade-migrate/lifecycle-policy.mdx
platform_versioned_docs/version-4.3.0/install/upgrade-migrate/lifecycle-policy.mdx
platform_versioned_docs/version-4.4.0/install/upgrade-migrate/lifecycle-policy.mdx
src/theme/DocSidebar/Desktop/Content/index.js

- update platform support matrix to HTML table same as `vCluster`
- move the support matrix to a partial
https://deploy-preview-1165--vcluster-docs-site.netlify.app/docs/platform/install/upgrade-migrate/lifecycle-policy#platform-supported-versions
Closes DOC-959
@netlify /docs

chore: platform lifecycle policy update

---

vcluster/deploy/control-plane/binary/manage.mdx
vcluster/deploy/worker-nodes/private-nodes/manage.mdx

Closes DOC-954
Closes ENG-9114
@netlify /docs

add docs on standalone control plane node removal for HA

---

vcluster/deploy/worker-nodes/private-nodes/manage.mdx

ENG-9061 | Change phrasing on private nodes upgrade description

---

docs/_partials/vcluster_supported_versions.mdx

[Preview Link](https://deploy-preview-1190--vcluster-docs-site.netlify.app/docs/vcluster/deploy/upgrade/supported_versions)
Closes ENG-8903
@netlify /docs

chore: add 0.28 and 0.29 releases

---

vcluster/deploy/upgrade/supported_versions.mdx

Closes ENG-7945
@netlify /docs

update compatibility matrix for 1.34
