loft-sh/vcluster-docs

netlify.toml
Fixed DOC-40
Test to see if using :splat with external URL works. May have to redirect * to legacy landing page instead.
**Old URLs redirect to current:**
**Section tests:**
Any page in the section should redirect to same page in v0.19 docs
Individual pages:
=> DOC-40 add redirects for google search result link

docs/vcluster/guides/0-20-migration.mdx, docs/vcluster/vcluster-yaml/README.mdx
Fixes DOC-31
Overview section:
- add list of steps with links to page anchors
- move release notes link to beta admonition
Convert section:
- add `> vcluster.yaml` to example so structure matches the command syntax above
Related content:
- add link to release notes
------
vcluster-yaml section landing page:
- add link to conversion guide
Deploy previews:
- https://deploy-preview-90--vcluster-docs-site.netlify.app/docs/vcluster/vcluster-yaml/
- https://deploy-preview-90--vcluster-docs-site.netlify.app/docs/vcluster/guides/0-20-migration
=> Tweaks to conversion guide

docs/_fragments/quickstart/secret-kubeconfig.mdx
Linux only accepts -d while Mac accepts both -D and -d.
Resolves https://github.com/loft-sh/vcluster-docs/issues/94
=> Change base64 decode flag to lowercase

docs/vcluster/vcluster-yaml/control-plane/components/backing-store/database/external.mdx
=> DOC-58: Add MySQL example to external database config page

sidebars.js, src/css/content/markdown.scss, src/css/sidebar.scss, src/theme/DocSidebar/Desktop/Content/styles.module.css
- Add right-pointing chevrons to top level product selections
- Change all other chevrons to down/up instead of right/down
- Unify font sizes for different menu items (some where larger?)
- Fix the width gap between the version/product selectors and the rest of the menu
- Add border underneath version/product selectors (to compensate for the lack of background)
- Fix vcluster.yaml logical grouping title styles (more distinct from the other items)
- Fix markdown h<n> line heights
(Corresponds to DOC-93)
=> Style changes and fixes (DOC-93)

vcluster/_partials/deploy/install-beta-cli.mdx
This is used in platform quickstart docs that proceed to use a command that is not available in v0.20.0-beta.1.
=> Update beta CLI install partial

platform/_partials/install/upgrade-v3-v4.mdx, platform/_partials/install/upgrade.mdx, platform/manage/upgrade-platform.mdx
https://deploy-preview-176--vcluster-docs-site.netlify.app/docs/platform/manage/upgrade-platform
Resolves ENG-3992
=> Document how to upgrade from v3 to v4 regarding project prefix

vcluster/deploy/topologies/isolated-workloads.mdx
Added an info box about setting `--expose-local=false` when running `vcluster create` locally.
Also added a missing yaml annotation to the last code block.
Preview link: https://deploy-preview-187--vcluster-docs-site.netlify.app/docs/vcluster/deploy/topologies/isolated-workloads
=> Updated isolated workloads formatting and info for local deployment

platform/_partials/install/upgrade-v3-v4.mdx
namespace must be specified when upgrading from v3 to v4
part of DOC-100
Signed-off-by: Rohan CJ <rohantmp@gmail.com>
=> fix: specify namespace in upgrading v3 to v4 doc

platform/_partials/install/upgrade-v3-v4.mdx
Link to the section containing the `loft` namespace: https://deploy-preview-198--vcluster-docs-site.netlify.app/docs/platform/manage/upgrade-platform#upgrading-from-v3x-to-v40
=> Added namespace to v3 to v4 upgrade instructions

platform/manage/oidc-provider.mdx
Fixes DOC-215
preview: https://deploy-preview-207--vcluster-docs-site.netlify.app/docs/platform/manage/oidc-provider
=> Add OIDC client secrets docs

vcluster/integrations/pod-identity/_category_.json, vcluster/integrations/pod-identity/_code/eks-pod-identity.sh, vcluster/integrations/pod-identity/_code/eks-pod-identity.tf, vcluster/integrations/pod-identity/_code/gcs-list-buckets-deployment.yaml, vcluster/integrations/pod-identity/_code/get-resource-name.sh, vcluster/integrations/pod-identity/_code/gke-workload-identity.sh, vcluster/integrations/pod-identity/_code/pod-identity-vcluster.yaml, vcluster/integrations/pod-identity/_partials/get-resource-name.mdx, vcluster/integrations/pod-identity/eks-pod-identity.mdx, vcluster/integrations/pod-identity/gke-workload-identity.mdx
Preview: https://deploy-preview-200--vcluster-docs-site.netlify.app/docs/platform/integrations/gke-workload-identity
=> ENG-4153 | Document setting up GKE Workload Identity/EKS Pod Identity

src/css/sidebar.scss
This change provides a visual means to support collapsible sections with the PRO tag. Currently, doing this causes visual issues.
As a result, this change also changes the style of the PRO tag in order to support this. Namely - the PRO tag no longer sticks to the right edge of the screen.
Here are some screenshots:
=> Changes to PRO tags

src/css/content/markdown.scss
This fixes some issues related to section highlighting.
Before:
After:
=> Fixed issues with section highlighting (:target)

vcluster/manage/accessing-vcluster.mdx
when editing the exportKubeConfig.server property you have to specify the port number as well, otherwise an error is thrown from the vcluster cli as there are not 2 instances of a : in the path. This change updates the documentation to include the port number.
see [pkg/cli/connect_helm.go](https://github.com/loft-sh/vcluster/blob/450e5288b68b728222acf5d0046b529a79ac6c8d/pkg/cli/connect_helm.go#L372)
```
splitted := strings.Split(cluster.Server, ":")
if len(splitted) != 3 {
return nil, fmt.Errorf("unexpected server in kubeconfig: %s", cluster.Server)
}
```
=> vcluster cli throws an error if exportKubeConfig.server does not have a port number when set

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded.mdx
Fixes Linear issue: `DOC-224`
Existing docs:
- https://www.vcluster.com/docs/vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded
Pages fixed:
- https://deploy-preview-238--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded
=> Adding changed to yaml for embedded etcd

vcluster/integrations/metrics/metrics-server.mdx
Documentation should reflect changes made in https://github.com/loft-sh/vcluster/pull/1903
`observability --> integrations`
=> [0.21] fix: observability deprecated in beta.12

.github/styles/Loft/no-vcluster-platform.yml, .vale.ini
Closes DOC-292
- a new vale rule suggesting usage of `the platform` instead of `vcluster platform`
- swapping vale level to `warning` which brings more rules into scope and helps benefit from vale checks.
=> feat: add vale rule and bump detect settings to warning

platform/_partials/install/login-after-helm-install.mdx, platform/install/helm.mdx
Improve clarity and usability of the `helm` installation documentation instructions.
Docs Link: https://deploy-preview-285--vcluster-docs-site.netlify.app/docs/platform/install/helm
Closes DOC-268, DOC-274
=> feat: improve helm installation process

.github/styles/Google/WordList.yml, .github/styles/config/vocabularies/Loft/accept.txt, .vale.ini, platform/_partials/auth/disable-password-auth.mdx, platform/_partials/auth/sso/dex/config.mdx, platform/_partials/auth/sso/dex/connectors/generic.mdx, platform/_partials/auth/sso/dex/hostname.mdx, platform/_partials/auth/sso/generic.mdx, platform/_partials/auth/sso/github.mdx, platform/_partials/auth/sso/gitlab.mdx, platform/_partials/auth/sso/google.mdx, platform/_partials/auth/sso/ldap.mdx, platform/_partials/auth/sso/microsoft.mdx, platform/_partials/auth/sso/oidc.mdx, platform/_partials/auth/sso/okta.mdx, platform/_partials/auth/sso/saml.mdx, platform/_partials/install/multiple-sso.mdx, platform/configure/single-sign-on/group-sync.mdx, platform/configure/single-sign-on/overview.mdx
Closes DOC-279, DOC-280, DOC-281, DOC-282
```text
- Single Sign On (SSO)
- Overview
- SSO Providers
- GitHub
- GitLab
- Google
- LDAP
- Microsoft
- Okta
- OpenID Connect
- Other (Dex)
- SAML
- Multiple SSO Providers
- SSO Group Sync
```
[SSO Section Preview](https://deploy-preview-305--vcluster-docs-site.netlify.app/docs/platform/configure/single-sign-on/overview)
> [!IMPORTANT]
> https://github.com/loft-sh/vcluster-docs/pull/303 must be merged first
=> feat: review sso configuration section (#279) 

docusaurus.config.js
This pull request includes a small change to the `docusaurus.config.js` file, adding an announcement bar to inform users about the availability of Platform 4.0. and directing to the upgrade guide.
[Banner Preview](https://deploy-preview-277--vcluster-docs-site.netlify.app/docs/)
https://github.com/loft-sh/vcluster-docs/pull/311
Closes DOC-261
=> feat: add banner announcing platform v4.0

.github/workflows/reviewdog.yaml
- using space as separator (default) didn't work with reviewdog
- swapping to comma as separator helpd solve the issue where reviewdog action was not able to parse the files correctly
- setting filter_mode to `file` forces reviewdog to report all errors before  exiting with 0
=> fix: file detection and reviewdog configuration

vcluster/deploy/security/fips.mdx
Fixes ENG-4916
Changed page:
- https://deploy-preview-328--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/security/fips#running-vcluster-fips-compliant
=> dx: Add info box containing version change in FIPS docs

docusaurus.config.js, package-lock.json, package.json, src/css/theme.scss, src/theme/DocSidebar/Desktop/Content/styles.module.css
Closes DOC-308
* Enabled dark mode, including mode switching and respecting the user's preferred color scheme
* Bumped docusaurus  to  `v3.3.2` 
The CSS is a bit hacky, I had to override a few styles aka `!important`, but it works.
[Docs Preview](https://deploy-preview-327--vcluster-docs-site.netlify.app/docs/)
=> feat: dark mode (#308)

vcluster/_partials/deploy/install-cli-beta.mdx
Not sure why its different the usual ones where downloads are after the tag :/
Found this while trying to install.
=> Update wrong release url

docusaurus.config.js
Closes DOC-328
[Docs Preview](https://deploy-preview-342--vcluster-docs-site.netlify.app/docs/)
=> chore: github icon points to the vcluster repo instead of docs

.github/styles/Google/Headings.yml, .github/styles/Loft/code-blocks-language.yml, vcluster/_partials/deploy/deploy.mdx, vcluster_versioned_docs/version-0.20.0/_partials/deploy/deploy.mdx
Closes DOC-316
[Deploy vCluster Preview versioned](https://deploy-preview-343--vcluster-docs-site.netlify.app/docs/vcluster/deploy/basics/?x3=2)
[Deploy vCluster Preview main](https://deploy-preview-343--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/basics?x3=2)
=> feat: simplify helm install  command and update vale settings

platform/install/advanced/air-gapped.mdx
Closed DOC-325
Docs Preview: https://deploy-preview-345--vcluster-docs-site.netlify.app/docs/platform/install/advanced/air-gapped#offline-images
=> feat: add warning about deploying external charts in airgapped environments

vcluster/_fragments/how-does-syncing-work.mdx, vcluster/_fragments/sync-from-host-resources.mdx, vcluster/_fragments/sync-to-host-resources.mdx, vcluster/configure/vcluster-yaml/sync/README.mdx, vcluster/configure/vcluster-yaml/sync/from-host/README.mdx, vcluster/configure/vcluster-yaml/sync/to-host/README.mdx, vcluster/introduction/architecture.mdx
Updated https://deploy-preview-329--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/
Also updated but the content is duplicated from above.
https://deploy-preview-329--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/to-host
https://deploy-preview-329--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/from-host
=> Update explaining syncing and bi-directional syncing

vcluster/_partials/quick-start-guide/explore-features.mdx, vcluster_versioned_docs/version-0.20.0/_partials/quick-start-guide/explore-features.mdx
The IngressClasses summary is incorrect and the example is misleading.
=> Fix IngressClasses example

platform/install/advanced/air-gapped.mdx
Closes DOC-334
Docs Preview: https://deploy-preview-346--vcluster-docs-site.netlify.app/docs/platform/install/advanced/air-gapped#supported-kubernetes-versions
=> feat: clarify supported kubernetes versions for airgapped installation

.github/styles/Google/Headings.yml
Exclude `Pro` from capitalization requirement in the Markdown headings.
Closes DOC-341
=> chore: add exception to vale rule for capitalization

vcluster/configure/vcluster-yaml/control-plane/other/advanced/workload-service-account.mdx
Call out that these configuration is overridden by the `sync.toHost.serviceAccounts: enabled` configuration.
=> Update workload service account page

src/js/details-clicks.js
Closes DOC-309
- Enable users and support staff to quickly copy `vCluster-config` YAML from config sections.
- Makes it easier to work with configurations by allowing copy-paste, helping users get started with vCluster more efficiently.
[Config reference Preview](https://deploy-preview-350--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/)
[Short clip showing how to use the feature](https://us02web.zoom.us/clips/share/HlynFVi1wYfSfHtxFcMRa3x3baL7-pamxK84V-ys5Gq8tqRQvwOBc44E0S5ASXG4nlyoThbk.lyM7UtqyB13Zglsi)
=> feat: copy button on yaml configuration parts

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/deploy.mdx, vcluster_versioned_docs/version-0.21.0/configure/vcluster-yaml/control-plane/components/backing-store/etcd/deploy.mdx
Closes DOC-326
[Backing Store Preview](https://deploy-preview-359--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/)
=> docs: adding info about etcd migration path for pro users

.github/styles/config/vocabularies/Loft/accept.txt, docs/_partials/managed_k8s_install_vcluster.mdx, vcluster/deploy/environment/gke.mdx
Closes DOC-351
[Deploy vCluster on GKE Preview](https://deploy-preview-368--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/gke)
=> feat: deploy vCluster on GKE

vcluster/_partials/quick-start-guide/view-host-resources.mdx, vcluster_versioned_docs/version-0.20.0/_partials/quick-start-guide/view-host-resources.mdx, vcluster_versioned_docs/version-0.21.0/_partials/quick-start-guide/view-host-resources.mdx
Closes DOC-207
[Main Branch Docs Preview](https://deploy-preview-333--vcluster-docs-site.netlify.app/docs/vcluster/next/#view-resources-inside-the-host-cluster:~:text=the%20host%20cluster.-,vCluster%20Control%20Plane,-The%20vCluster%20my%2Dcluster%2D0)
[0.20 Version Docs Preview](https://deploy-preview-333--vcluster-docs-site.netlify.app/docs/vcluster/0.20.0/#view-resources-inside-the-host-cluster:~:text=the%20host%20cluster.-,vCluster%20Control%20Plane,-The%20vCluster%20my%2Dcluster%2D0)
[0.21 Version Docs Preview](https://deploy-preview-333--vcluster-docs-site.netlify.app/docs/vcluster/#view-resources-inside-the-host-cluster:~:text=the%20host%20cluster.-,vCluster%20Control%20Plane,-The%20vCluster%20my%2Dcluster%2D0)
=> feat: adding info about stateful set (#207)

docusaurus.config.js
bump platform version to `v4.2`
Closes DOC-370
=> chore: bump platform version to latest

hack/vcluster/partials/main.go, vcluster/_partials/config/integrations/certManager.mdx
adds `integrations/certManager` so we generate a partial containing certManager feature configuration.
There is another PR coming that gets rid of hardcoded paths from vCluster partial generation script.
Deploy preview https://deploy-preview-397--vcluster-docs-site.netlify.app/
<!--Add the Github or Linear ticket reference>
Closes DOC-368
=> generate partial for certManager config

docusaurus.config.js
Update announcement banner with new releases
Merge when the [changelog](https://www.vcluster.com/releases/en/changelog?hideLogo=true&hideMenu=true&theme=dark&embed=true&c=vCluster) versions are ready.
Closes DOC-371
=> chore: update announcement banner for `v4.2` and `v0.22`

vcluster/_fragments/integrations/cert-manager.mdx, vcluster_versioned_docs/version-0.22.0/_fragments/integrations/cert-manager.mdx
Cert manager integration points to creating ClusterIssuer on host cluster and it should be on virtual cluster.
[Setup the integration](https://deploy-preview-407--vcluster-docs-site.netlify.app/docs/vcluster/integrations/certmanager/#setup-the-integration)
Closes DOC-381
=> fix: apply to the virtual cluster

platform/configure/cost-control.mdx, platform/install/advanced/air-gapped.mdx
Add network requirements for the cost control dashboard. Issues with metrics federation were discovered on loft.rocks, and it was due to the connected clusters being private GKE clusters. Similar issues could be expected for air gapped clusters, depending on how their firewalls are configured.
[Cost Control Dashboard](https://deploy-preview-409--vcluster-docs-site.netlify.app/docs/platform/configure/cost-control)
[Deploy in Air-Gapped Environments](https://deploy-preview-409--vcluster-docs-site.netlify.app/docs/platform/install/advanced/air-gapped/#resource-requirements)
Closes DOC-382
=> Add Cost Control Dashboard Network Requirements

vcluster/_partials/quick-start-guide/deploy-resources.mdx, vcluster_versioned_docs/version-0.20.0/_partials/quick-start-guide/deploy-resources.mdx, vcluster_versioned_docs/version-0.21.0/_partials/quick-start-guide/deploy-resources.mdx, vcluster_versioned_docs/version-0.22.0/_partials/quick-start-guide/deploy-resources.mdx
Just a little typo fix on something I saw while reading the docs.
I'm not very sure about changing the older versions, but here it is...
=> Fix typo for deployment name in the quickstart guide

platform/install/supported_versions.mdx, vcluster/deploy/upgrade/_category_.json, vcluster/deploy/upgrade/supported_versions.mdx, vcluster/deploy/upgrade/upgrade-version.mdx
=> Move supported versions pages

docusaurus.config.js, vcluster/deploy/upgrade/upgrade-version.mdx
When search results lead to the `0.19` version, the page is no correctly loaded. What happens is that the search result shows "page not found" and only after refresh, the page is loaded.
Using the `externalUrlRegex` to load all the searches related to the `0.19` version in a separate window, using `window.location.href` results in the search on `0.19` to load correctly.
The drawback of this is that search results for `0.19` load a bit slower because they need to render in a separate window.
To test the change go to the [preview link](https://deploy-preview-416--vcluster-docs-site.netlify.app/docs/) and insert serach for "synced resources", the top search should take you to the `0.19` docs opening in new tab/window (depending on your browser configuraiton).
Searches for the current version …
=> fix(search): fixing pages not loading after search

vcluster/_fragments/sleepmode-deployment-example.mdx, vcluster/_fragments/sleepmode-ingress-example.mdx, vcluster/configure/vcluster-yaml/experimental/_code/sleepmode-deployment-config.yaml, vcluster/configure/vcluster-yaml/experimental/_code/sleepmode-deployment-examples.yaml, vcluster/configure/vcluster-yaml/experimental/_code/sleepmode-host-ingress-config.yaml, vcluster/configure/vcluster-yaml/experimental/_code/sleepmode-ingress-examples.yaml, vcluster/configure/vcluster-yaml/experimental/isolated-control-plane.mdx, vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/experimental/native-sleep-mode.mdx
Adds tutorials for setting up vcluster with sleep mode using deployments and with an Ingress controller on the host.
[Preview Link](https://deploy-preview-414--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/experimental/native-sleep-mode)
Closes DOC-378
=> Adds sleep mode tutorials

platform/install/environments/_category_.json, platform/install/environments/gcp.mdx, platform/install/gcp.mdx
How to set up the platform on a GKE cluster, including cluster creation.
[Deploy vCluster Platform on Google Cloud](https://deploy-preview-411--vcluster-docs-site.netlify.app/docs/platform/install/environments/gcp)
Closes DOC-383
=> feat(platform): install platform on GKE

.github/styles/Google/WordList.yml
Word list rules still trigger even if text is enclosed in backticks
N/A
Closes DOC-
=> chore: remove url from google word list

platform/_partials/install/install-next-steps.mdx, platform/install/environments/gcp.mdx
- remove create virtual cluster instructions
- make the load balancer and dns steps optional
- add sleep & wakeup to the next steps section
- mention using Google for SSO
- remove workload identity
- cluster creation command is idempotent
- add link to configuring TLS
- improve DNS commands
[Deploy vCluster Platform on Google Cloud](https://deploy-preview-421--vcluster-docs-site.netlify.app/docs/platform/install/environments/gcp)
Closes DOC-390
=> refactor(gcp-platform): address feedback from first PR

.github/styles/config/vocabularies/Loft/accept.txt
DevSpace as a product should have capital D and S, whereas if used as CLI, should be enclosed in backticks and written in lowercase.
N/A
Closes DOC-395
=> chore(vale): add devspace to vale exceptions

.github/styles/Loft/centralize-partials-fragments.yml, docs/index.mdx, vcluster/_partials/deploy/deploy.mdx, vcluster_versioned_docs/version-0.21.0/_partials/deploy/deploy.mdx, vcluster_versioned_docs/version-0.22.0/_fragments/integrations/cert-manager.mdx, vcluster_versioned_docs/version-0.22.0/_partials/deploy/deploy.mdx, vcluster_versioned_docs/version-0.22.0/deploy/environment/gke.mdx, vcluster_versioned_docs/version-0.22.0/deploy/topologies/air-gapped.mdx
Add vale rule to block use of site in local partials. Also fix existing partials to conform to the rule.
Didn't fix usage of fragments because there were too many existing violations.
>We want to avoid using `@site` directive to reference docs specific `_partials` (references inside vcluster, platform or versioned folders). 
>
>To make this check automated, we would like to a create a vale rule to capture and enforce the logic. 
https://deploy-preview-425--vcluster-docs-site.netlify.app/docs/
Closes DOC-287
=> feat: Add vale rule to block use of site in local partials

.github/styles/Google/Headings.yml, vcluster/configure/vcluster-yaml/control-plane/components/host-path-mapper.mdx, vcluster/introduction/architecture.mdx, vcluster_versioned_docs/version-0.20.0/configure/vcluster-yaml/control-plane/components/host-path-mapper.mdx, vcluster_versioned_docs/version-0.20.0/introduction/architecture.mdx, vcluster_versioned_docs/version-0.21.0/configure/vcluster-yaml/control-plane/components/host-path-mapper.mdx, vcluster_versioned_docs/version-0.21.0/introduction/architecture.mdx, vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/control-plane/components/host-path-mapper.mdx, vcluster_versioned_docs/version-0.22.0/introduction/architecture.mdx
Updated the docs for current and previous version (v0.21 & v0.22) to include detailed installation instructions for hpm. 
- [Architecture](https://deploy-preview-431--vcluster-docs-site.netlify.app/docs/vcluster/next/introduction/architecture)
- [HostPath Mapper](https://deploy-preview-431--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/host-path-mapper)
Closes DOC-393
=> Update hpm installation instructions under versioned

.github/workflows/reviewdog.yaml
Currently vale checks content of all docs, but some of them are autogenerated and here vale checks create false positives. We should configure vale to ignore folders with the autogenerated documentation.
N/A
Closes DOC-402
=> chore(vale): add autogenerated docs to vale ignore list

CONTRIBUTING.md
- vale setup and usage
- consistency and docs flow guidelines
- clarify styling rules
N/A
Closes DOC-273
=> docs(styling): extend styling guidelines section

CONTRIBUTING.md, vcluster/contribute/_category_.json, vcluster/contribute/contribute.mdx, vcluster_versioned_docs/version-0.20.0/contribute/_category_.json, vcluster_versioned_docs/version-0.20.0/contribute/contribute.mdx, vcluster_versioned_docs/version-0.21.0/contribute/_category_.json, vcluster_versioned_docs/version-0.21.0/contribute/contribute.mdx, vcluster_versioned_docs/version-0.22.0/contribute/_category_.json, vcluster_versioned_docs/version-0.22.0/contribute/contribute.mdx
Previously, only `the platform` docs had `Contribute` section. Since now, we have improved the contribution guidelines, we are referencing it in `vCluster` docs as well, all versions.
- [Contribute to Platform Docs](https://deploy-preview-438--vcluster-docs-site.netlify.app/docs/platform/contribute/)
- [Contribute to vCluster Docs](https://deploy-preview-438--vcluster-docs-site.netlify.app/docs/vcluster/contribute/)
> [!NOTE]
> make sure to select all vCluster versions
Closes DOC-406
=> chore: add contribution doc to vcluster and platform

.github/pull_request_template.md
Adding info about dealing with `vale` errors to the PR template.
Closes DOC-407
=> chore: add info about using vale

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/database/external.mdx, vcluster_versioned_docs/version-0.21.0/configure/vcluster-yaml/control-plane/components/backing-store/database/external.mdx, vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/control-plane/components/backing-store/database/external.mdx
fix import for database config reference 
[Next version Preview](https://deploy-preview-440--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/database/external/)
[v0.21 Preview](https://deploy-preview-440--vcluster-docs-site.netlify.app/docs/vcluster/0.21.0/configure/vcluster-yaml/control-plane/components/backing-store/database/external/)
[v0.22 Preview](https://deploy-preview-440--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/control-plane/components/backing-store/database/external/)
=> fix: database config reference

docs/_partials/base-prerequisites.mdx
- Added a line to [reflect active voice ](https://developers.google.com/style/voice)for prerequisites
[Link to docs ](https://deploy-preview-441--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/experimental/native-sleep-mode/#prerequisites)
> **Note**: This PR is just for test purposes. Even though the text is changed in a partial doc, it actually just applies to one spot in the docs. I would have to update it in another partial within the `install` folder to apply it to the other prerequisite texts in published docs. 
n/a
=> Update prerequisites to reflect active voice

vcluster/configure/vcluster-yaml/experimental/native-sleep-mode.mdx, vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/experimental/native-sleep-mode.mdx
[v0.22](https://deploy-preview-446--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/experimental/native-sleep-mode)
[main](https://deploy-preview-446--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/experimental/native-sleep-mode)
Closes DOC-412
=> adds warning not to double configure sleep mode

src/css/sidebar.scss, vcluster/integrations/certManager.mdx, vcluster/integrations/kubevirt.mdx
The PRO label is now applied to the `::after` pseudo-selector of the actual `.pro` element. This is to prevent a collision with Docusaurus' own `::after`, which draws the submenus generally.
This affects the way that the PRO label is positioned (added comments for future generations).
Additionally, I have implemented some changes for a more consistent look for the PRO tags across different sections (though, some small and mysterious quirks of style do remain)
Closes DOC-397
Support for collapsible pro items (**none currently exist, this is a test**):
Other pro tags:
=> Improved PRO label drawing, and fixed a display bug

.github/pull_request_template.md, platform/configure/config.mdx, platform/configure/custom-branding.mdx, platform/how-to/oidc-provider.mdx, platform/install/gitops.mdx, platform/install/helm.mdx, platform/integrations/rancher/rancher-integration.mdx, vcluster/integrations/github-actions/_category_.json, vcluster/integrations/github-actions/preview-environments.mdx, vcluster/integrations/github-actions/pull-requests.mdx
- Some of the titles use a mix of title case and sentence case. Since we are treating "Platform" as a proper noun, I left it capitalized. However, other terms like "integration" or "configuration" are not proper nouns, so they should likely be in lowercase to align with sentence case style.
- Slight rewrite to text and added commas for clarity
> **Note**: The term "Platform" is not formatted consistently throughout the document. I opted to use it as a proper noun to align with the document's headings ( but it could go either way). Additionally, according to [the Google style guide](https://developers.google.com/style/ui-elements), UI elements should be formatted in bold typeface. There are a few instances where this formatting should be updated to match the style guide.
- [Update headings …
=> Adjust title headings

vcluster/manage/sleep-wakeup.mdx, vcluster_versioned_docs/version-0.20.0/manage/sleep-wakeup.mdx, vcluster_versioned_docs/version-0.21.0/manage/sleep-wakeup.mdx, vcluster_versioned_docs/version-0.22.0/manage/sleep-wakeup.mdx
Fixing sleep and wake-up commands and doc.
[Sleep & Wakeup vCluster](https://deploy-preview-451--vcluster-docs-site.netlify.app/docs/vcluster/next/manage/sleep-wakeup)
Closes DOC-417
=> fix(cli): fixing vcluster sleep and wakeup commands

netlify.toml
When users type part of url in the url search bar, the old settings would redirect them to the `v0.19` docs. Changing the redirects to use only recent version of the docs and removing redirects that are no longer there.
[What are virtual clusters?](https://deploy-preview-453--vcluster-docs-site.netlify.app/docs/)
Try to type in the url search bar one of the redirects and see if it resolves to url correctly
Closes DOC-415
References DOC-419
=> feature: adjust netlify redirects to latest

platform/administer/clusters/connect-cluster.mdx, platform/use-platform/virtual-clusters/add-virtual-clusters.mdx
Adds more context to adding host clusters to a platform instance.
[Connect a Cluster](https://deploy-preview-454--vcluster-docs-site.netlify.app/docs/platform/administer/clusters/connect-cluster?x0=1)
Closes DOC-423
=> fix(platform): clarify hostcluster add

vcluster/configure/vcluster-yaml/experimental/native-sleep-mode.mdx, vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/experimental/native-sleep-mode.mdx
Adds example so native sleep mode docs look more like the Kube Virt integration page
None
=> Adds basic example at top of native sleep mode docs

hack/vcluster/partials/main.go, vcluster/_fragments/sync-from-host-configmap-example.mdx, vcluster/_fragments/sync-from-host-namespaced-custom-resources-example.mdx, vcluster/_fragments/sync-from-host-resources.mdx, vcluster/_fragments/sync-from-host-secret-example.mdx, vcluster/_partials/config/sync/fromHost/configMaps.mdx, vcluster/_partials/config/sync/fromHost/secrets.mdx, vcluster/configure/vcluster-yaml/sync/from-host/configmaps.mdx, vcluster/configure/vcluster-yaml/sync/from-host/custom-resources.mdx, vcluster/configure/vcluster-yaml/sync/from-host/secrets.mdx
1. Adds docs for  config maps from host sync
2. Adds a fragment with a guide how to use config map from host sync
3. Adds docs for secrets from host sync
4. Adds a fragment with a guide how to use secret from host sync
5. Adds docs for namespaced custom resources from host sync
2. Adds a fragment with a guide how to use namespaced custom resources from host sync
Closes DOC-401
=> From host sync docs with examples

docs/_partials/vcluster_supported_versions.mdx
- remove latest release column from vcluster support matrix table
- since this is a partial, it will affect all the documents that reference it
```plaintext
vcluster_versioned_docs/version-0.20.0/deploy/supported_versions.mdx
vcluster_versioned_docs/version-0.22.0/deploy/supported_versions.mdx
vcluster_versioned_docs/version-0.21.0/deploy/supported_versions.mdx
vcluster/deploy/upgrade/supported_versions.mdx
```
[vCluster releases](https://deploy-preview-470--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/upgrade/supported_versions#vcluster-releases)
Closes DOC-461
=> feat: remove latest release column from vcluster support matrix table

vcluster/configure/vcluster-yaml/export-kube-config.mdx
Added port in server url as per https://github.com/loft-sh/vcluster/blob/main/pkg/cli/connect_helm.go#L366
Closes DOC-
=> added the port in server url for exported kubeconfig

.github/styles/Google/FirstPerson.yml, vcluster/configure/vcluster-yaml/export-kube-config.mdx, vcluster_versioned_docs/version-0.22.0/configure/vcluster-yaml/export-kube-config.mdx
Follow up PR to address linter issues and text from [PR 445](https://github.com/loft-sh/vcluster-docs/pull/475/files)
[Link to preview](https://deploy-preview-477--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/export-kube-config/) 
Closes DOC-466
=> fix: update doc to address linter notes

src/css/general.scss, src/css/sidebar.scss, vcluster/_partials/admonitions/pro-advanced-admonition.mdx, vcluster/_partials/admonitions/pro-starter-admonition.mdx, vcluster/_partials/admonitions/pro-ultimate-admonition.mdx
- rename sidebar pro label to enterprise
- introduce custom enterprise admonitions
The admonitions can be referenced as separate partials on any page. Will be versioned with vcluster versions.
N/A
Closes DOC-452
=> feat: enterprise pricing admonitions

platform/_partials/vcluster/share-cli.mdx, platform/_partials/vcluster/share-ui.mdx, platform/use-platform/virtual-clusters/add-virtual-clusters.mdx, platform/use-platform/virtual-clusters/create/create-no-template.mdx, platform/use-platform/virtual-clusters/create/create-with-template.mdx, platform/use-platform/virtual-clusters/manage-access.mdx, platform/use-platform/virtual-clusters/retrieve-kube-config.mdx
Makes the Ui procedure into an partial and adds CLI step
[Link to preview](https://deploy-preview-476--vcluster-docs-site.netlify.app/docs/platform/use-platform/virtual-clusters/manage-access/?x0=2)
Closes DOC-222
=> fix: Add UI and CLI options for share

platform/api/authentication.mdx, platform/api/resources/config.mdx, platform/api/resources/team.mdx, platform/api/resources/user.mdx
Fixed minor changes in documentation that were still referring to loft instead of vCluster platform
Closes DOC-
=> Fixed minor documentation errors in vcluster platform(v4.x)

.github/styles/Google/AmericanSpelling.yml
- Add spellings to vale list
- fantasise vs. fantasize
- idolise vs. idolize
=> chore(vale): add missing American spelling words

platform/_partials/cluster/connect-helm.mdx
The helm instructions for the agent installation use "vcluster-platform" as target namespace. The same namespace needs to be set in the Cluster resource in the .spec.managementNamespace otherwise upgrades and configuration changes of the agent will fail.
[Document Preview](https://deploy-preview-493--vcluster-docs-site.netlify.app/docs/platform/administer/clusters/connect-cluster?x0=3)
=> Update connect-helm.mdx - include managementNamespace field in the Cluster resource

platform/configure/advanced/audit.mdx
For audit logging persistence, it was hidden that PVC method was not supported, so made it a call out. 
Closes ENG-3792
=> Update HA and PVC incompatibility to make it more obvious

vcluster/configure/vcluster-yaml/export-kube-config.mdx
Update Export kubeConfig docs so they reflect the latest implementation changes from https://github.com/loft-sh/vcluster/pull/2542. We have added a new `exportKubeConfig.additionalSecrets` config and deprecated `exportKubeConfig.secret`.
[Export kubeconfig Preview](https://deploy-preview-504--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/export-kube-config/)
Closes ENG-6080
=> Update Export kubeconfig docs

docusaurus.config.js
Indicates which versions are out of support (EOL).
https://deploy-preview-509--vcluster-docs-site.netlify.app/docs/vcluster
Closes DOC-460
=> feat: clearly indicate which versions are out of support

staging/How to Enable Debug Logging for vCluster.mdx, staging/enable-debug-logging.mdx
=> vcluster-debug-logs

platform/administer/upgrade-migrate/migrate-to-hostcluster.mdx, platform/how-to/migrate-to-hostcluster.mdx
[Migrate the platform to a different cluster](https://deploy-preview-492--vcluster-docs-site.netlify.app/docs/platform/administer/upgrade-migrate/migrate-to-hostcluster)
Closes DOC-266
=> feat: migrate platform to a different kubernetes cluster

staging/airgaped-vcluster-deployment.mdx
Deploy vcluster in an air-gaped env without an internal helm repo
Closes DOC-
=> feat: create airgapped vcluster deployment docs

vcluster/deploy/basics.mdx
=> fix: prerequisites should be one word

.github/workflows/create-linear-issue.yaml
=> feat(ci): create a follow-up linear issue on a PR

vcluster/deploy/upgrade/supported_versions.mdx
- Update table to reflect support for 1.30 upwards.
Closes DOC-511
=> fix: update to include only 1.30 and higher

docusaurus.config.js
Revert this PR once release is announced.
Closes DOC-519
=> fix: mark 0.23 as stable until 0.24 release is announced

.github/workflows/create-linear-issue.yaml
Linear issues created from PRs will automatically have a `follow-up` label added to easier group them.
N/A
Closes DOC-
=> feat: add follow-up label in linear to all issues created from prs

docs/_partials/support_terminology.mdx, docs/_partials/vcluster_supported_versions.mdx, docusaurus.config.js, platform/install/supported_versions.mdx
- adding non-versioned partial with definitions of end-of-life support abbreviations.
- partial is reused between vcluster and platform.
- adjusting the eol/eos settings in dropdown and main label.
- [Platform supported versions](https://deploy-preview-541--vcluster-docs-site.netlify.app/docs/platform/install/supported_versions)
- [vCluster releases](https://deploy-preview-541--vcluster-docs-site.netlify.app/docs/vcluster/deploy/upgrade/supported_versions)
Closes DOC-518
=> feat: clarify end of life terminology in supported versions

vcluster/troubleshoot/_category_.json, vcluster/troubleshoot/etcd-compaction.mdx
- Follow up to [this PR](https://github.com/loft-sh/vcluster-docs/pull/519) to add compaction solution to docs
[Link to Preview](https://deploy-preview-548--vcluster-docs-site.netlify.app/docs/vcluster/next/troubleshoot/etcd-compaction?xetcd-nospace-alarm=1)
Closes DOC-504
=> refactor: add troublshooting for etcd nospace docs

vcluster/configure/vcluster-yaml/control-plane/components/coredns.mdx, vcluster/configure/vcluster-yaml/networking/resolve-dns.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/control-plane/components/coredns.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/networking/resolve-dns.mdx
- Update docs and add embedded CoreDNS to all code snippets
- Add enterprise label 
Closes DOC-422
=> fix: add missing code and label for embedded CoredDNS

vcluster/configure/vcluster-yaml/sleep-mode.mdx, vcluster/configure/vcluster-yaml/sync/from-host/configmaps.mdx, vcluster/configure/vcluster-yaml/sync/from-host/secrets.mdx, vcluster/deploy/environment/aks.mdx, vcluster/deploy/environment/eks.mdx, vcluster/deploy/environment/gke.mdx, vcluster/deploy/upgrade/supported_versions.mdx, vcluster/manage/sleep-wakeup.mdx
Update import paths for docs/_partials references
For example:
```diff
- import BasePrerequisites from '../../../docs/_partials/base-prerequisites.mdx';
+ import BasePrerequisites from '@site/docs/_partials/base-prerequisites.mdx';
```
This change is important for when we cut a new docs release, as these references will no longer
break when the file structure changes. The @site prefix ensures that the imports remain stable
across versions and directory restructuring.
https://deploy-preview-556--vcluster-docs-site.netlify.app/docs/
Closes DOC-527
=> chore: update non-versioned partials references

platform/install/helm.mdx
Fix wrong default password as it: https://github.com/loft-sh/loft-enterprise/blob/main/chart/values.yaml#L8
Wrong default password fix
Closes DOC-
=> fix: wrong default password when create platform using helm

vcluster/configure/vcluster-yaml/policies/pod-security-standard.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/policies/pod-security-standard.mdx
- Make text on profile policy a little clearer
- make inputs lowercase
[Link to Preview](https://deploy-preview-559--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/policies/pod-security-standard)
Closes DOC-525
=> fix: update policy profile doc

platform/api/_partials/resources/config/retrieve.mdx, platform/api/resources/config.mdx
- Remove outdated command for platform configs
[Link to Preview](https://deploy-preview-560--vcluster-docs-site.netlify.app/docs/platform/api/resources/config?x0=1)
Closes DOC-508
=> fix: update incorrect config command

.github/styles/Loft/headings-ids.yml
This is too noisy on changes.
N/A
Closes DOC-533
=> chore(vale): lower level on headings id rule to suggestion

platform/_partials/install/install-next-steps.mdx, platform/_partials/install/open-ports.mdx, platform/administer/clusters/advanced/monitoring.mdx, platform/administer/clusters/advanced/networking.mdx, platform/administer/clusters/connect-cluster.mdx, platform/install/advanced/air-gapped.mdx, platform/install/gitops.mdx, platform/install/helm.mdx, platform/install/quick-start-guide.mdx, vcluster/configure/vcluster-yaml/export-kube-config.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/export-kube-config.mdx
- Add clarity to open ports docs. 
- Add a networking section and also put content in troubleshooting section. 
> NOTE: I attempted to add some firewall information to this doc, but I'm not sure if it's correct. While we mention firewall considerations, we don't provide specific details, which is less than ideal for users. I've added some content but commented it out because I'm uncertain about its accuracy. Could you please review both the PR source and the rendered preview? I'm looking for clarity and information for the firewall section as well, as it would be beneficial to make this available to users.
- [Link to Preview - Troubleshooting](https://deploy-preview-508--vcluster-docs-site.netlify.app/docs/platform/administer/clusters/advanced/networking)
- [Link to Preview - Install …
=> (re)factor: update ports documentation

.github/workflows/create-linear-issue.yaml
Remove markdown comments from PR body for better readability in the linear issue.
Closes DOC-
=> feat(ci): remove markdown comments from PR body

staging/check_if_vcluster.mdx
A KB article on programmatic checking if you are connected to a vCluster or host cluster.
Closes DOC-
=> Check if you are connected to vCluster or host

platform/administer/clusters/advanced/networking.mdx, vcluster/configure/vcluster-yaml/control-plane/components/coredns.mdx, vcluster/deploy/environment/eks.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/control-plane/components/coredns.mdx, vcluster_versioned_docs/version-0.24.0/deploy/environment/eks.mdx
- Update pages to mention port `1053` should be open
Closes DOC-451
=> feat: missing port 1053 added to docs

vcluster/_fragments/eso.mdx
The ESO example was referencing a wrong version number.
part of ENG-6173
=> fix: reference correct version in ESO example

platform/administer/upgrade-migrate/migrate-to-hostcluster.mdx
- Add explicit instruction to scale up platform deployment after certificate application
- Clarify that platform external access can be via either `ingress` or `LoadBalancer`
- Fix inconsistency between migration and domain configuration documentation
- Improve migration process workflow to prevent extended downtime
[Migrate the platform to a different cluster](https://deploy-preview-579--vcluster-docs-site.netlify.app/docs/platform/administer/upgrade-migrate/migrate-to-hostcluster)
Closes DOC-536
=> fix: improve platform migration doc

.github/styles/Google/Colons.yml, .github/styles/config/vocabularies/Loft/accept.txt
- Google does allow capitalization after a colon if it's a full sentence. The colon rule assumes that capitalization is always wrong — which is not correct per Google or Microsoft's guide.
-  Add more acceptable words to list and alphabetize list
Closes DOC-
=> fix: updates to vale rules

vcluster/configure/vcluster-yaml/control-plane/deployment/statefulset.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/control-plane/deployment/statefulset.mdx
- Minor updates to comply with style guide
[Link to Preview](https://deploy-preview-571--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/control-plane/deployment/statefulset)
Closes DOC-514
=> fix: updates to image doc for clarity

.github/workflows/reviewdog.yaml
=> chore(ci): update vale rules to include platform versioned docs

vcluster/_fragments/patches.mdx
- Update the text related to patches
- Restructure doc for a bit more clarity
- Add further explanation for wildcards in patches and `context` variable
- Refine examples for clarity
- [Link to preview](https://deploy-preview-445--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/to-host/core/pods#patch)
N/A
=> refactor: update text on patches

vcluster_versioned_docs/version-0.24.0/_fragments/patches.mdx
- Back port to previous release version.
Closes DOC-553
=> chore: backport patches

platform/_partials/vcluster/air-gapped-helm-charts.mdx, platform/install/advanced/air-gapped.mdx, platform/use-platform/troubleshooting/troubleshooting.mdx, platform/use-platform/virtual-clusters/create/create-no-template.mdx, platform/use-platform/virtual-clusters/create/create-with-template.mdx
Originally an engineering issue, it was determined that documenting a procedure for hosting and using Helm charts in an air-gapped environment would be sufficient until more extensive improvements could be made to the platform as part of the [Standardize Air-gapped/private registry install](https://linear.app/loft/project/standardize-air-gappedprivate-registry-install-f439efbc2ef8/overview) project.
Closes ENG-6264
Closes DOC-494
=> feat: document the current procedure for offline helm charts

.github/workflows/backport-docs.yml
=> feat(ci): use backport action to backport docs between folders

.github/workflows/backport-docs.yml
=> fix(ci): ci reference needs full commit hash

vcluster/learn-how-to/configure-kai-scheduler.mdx
https://deploy-preview-619--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/configure-kai-scheduler/
Closes DOC-557
=> feat(vcluster): add how-to document about using NVIDIA KAI scheduler

vcluster/manage/accessing-vcluster.mdx, vcluster/manage/backup-restore.mdx, vcluster/manage/deploy-changes.mdx, vcluster/manage/sleep-wakeup.mdx, vcluster_versioned_docs/version-0.24.0/manage/accessing-vcluster.mdx, vcluster_versioned_docs/version-0.24.0/manage/deploy-changes.mdx, vcluster_versioned_docs/version-0.24.0/manage/sleep-wakeup.mdx
- Add a link from manual sleep to sleep mode page
[Link to Preview](https://deploy-preview-627--vcluster-docs-site.netlify.app/docs/vcluster/next/manage/sleep-wakeup)
Closes DOC-495
=> fix: add links for sleep mode

vcluster/configure/vcluster-yaml/policies/admission-control.mdx
https://deploy-preview-629--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/policies/admission-control
Part of ENG-6252
=> docs: add info about translated pod name in admission review

vcluster/configure/vcluster-yaml/networking/replicate-services.mdx
Explain how replicated services are cleaned up when they are removed from `networking.replicateServices.fromHost` config.
[Replicate services docs preview](https://deploy-preview-630--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/networking/replicate-services)
Closes DOC-418
=> Explain how replicated services are cleaned up

vcluster/_partials/what-are-virtual-clusters.mdx, vcluster_versioned_docs/version-0.24.0/_partials/what-are-virtual-clusters.mdx
- Following a chat with @deniseschannon , we should use the term "certified Kubernetes distribution". Applying to `stable` and `main` docs.
Closes DOC-
=> fix: slight rewording for intro for vcluster

vcluster/configure/vcluster-yaml/experimental/sync-settings.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/experimental/sync-settings.mdx
Removing documentation for the syncLabels field, which is no longer part of the confi.
Related to https://github.com/loft-sh/vcluster/issues/2718
#Closes DOC-
=> Remove syncLabels from the sync-settings.mdx

vcluster/configure/vcluster-yaml/sync/from-host/configmaps.mdx, vcluster_versioned_docs/version-0.23.0/configure/vcluster-yaml/sync/from-host/configmaps.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/sync/from-host/configmaps.mdx
- Small typo fix for sidebar
[Link to Preview](https://deploy-preview-643--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/sync/from-host/)
Closes DOC-580
=> fix: configmap sidebar

platform/administer/clusters/advanced/networking.mdx, platform/administer/monitoring/metrics.mdx, platform_versioned_docs/version-4.2.0/administer/clusters/advanced/networking.mdx, platform_versioned_docs/version-4.2.0/administer/monitoring/metrics.mdx
https://deploy-preview-646--vcluster-docs-site.netlify.app/docs/platform/administer/clusters/advanced/networking/#connect-kubernetes-to-the-platform
https://deploy-preview-646--vcluster-docs-site.netlify.app/docs/platform/next/administer/monitoring/metrics/#metrics
Closes DOC-579
=> feat(platform): add info about metrics endpoint

docs/_partials/deprecation-notice.mdx, vcluster/_partials/deploy/distros.mdx, vcluster/configure/vcluster-yaml/control-plane/README.mdx, vcluster/configure/vcluster-yaml/control-plane/components/distro/README.mdx, vcluster/configure/vcluster-yaml/control-plane/components/distro/k0s.mdx, vcluster/configure/vcluster-yaml/control-plane/components/distro/k3s.mdx, vcluster/configure/vcluster-yaml/control-plane/components/distro/k8s.mdx
- Add deprecation not for k0s and k3s
[Link to Preview](https://deploy-preview-656--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/)
Closes DOC-577
=> fix: add deprecation note

vcluster/configure/vcluster-yaml/control-plane/other/advanced/default-image-registry.mdx, vcluster/deploy/topologies/air-gapped.mdx
- Update instances `vcluster-images.txt` to `images.txt`
- I do not see `vcluster-optional-images.txt` in the doc set so did not replace this. Also only applied this to v.25. Not sure if this needs to back ported
[Link to Preview](https://deploy-preview-659--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/other/advanced/default-image-registry)
Closes DOC-535
=> fix: image refs for images.txt

vcluster/configure/vcluster-yaml/README.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/README.mdx
[main Preview](https://deploy-preview-660--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/#config-reference)
[0.24 Preview](https://deploy-preview-660--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/#config-reference)
Closes DOC-612
=> fix: add sleepMode to configReference

docusaurus.config.js, src/css/footer.scss
- Reduce footer for docs site
[Link to Preview](https://deploy-preview-657--vcluster-docs-site.netlify.app/docs/)
Closes DOC-606
=> fix: make docs page footer smaller

vcluster/deploy/flux.mdx
https://deploy-preview-602--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/flux
Closes DOC-360
=> feat(vcluster): add fluxcd installation for vcluster

vcluster/_fragments/integrations/istio.mdx
Waypoint proxy is no longer deployed automatically by vCluster.
=> update istio integration docs according to the changes made in v0.25.0-rc5

.github/styles/config/vocabularies/Loft/accept.txt, vcluster/_partials/deploy/fips-config.mdx, vcluster/deploy/security/fips.mdx, vcluster/deploy/topologies/air-gapped.mdx
https://deploy-preview-661--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/topologies/air-gapped
Closes DOC-
=> Update vcluster airgap docs

netlify.toml
This adds two new redirects for docs links in the platform UI.
Closes DOC-419
=> feat: Add additional permanent redirects for the platform UI

vcluster/deploy/upgrade/distro-migration.mdx, vcluster/deploy/upgrade/upgrade-version.mdx, vcluster/manage/deploy-changes.mdx
Migration guide from k3s to regular Kuberentes distro.
https://deploy-preview-663--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/upgrade/distro-migration
https://deploy-preview-663--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/upgrade/upgrade-version#optional-update-vclusteryaml
https://deploy-preview-663--vcluster-docs-site.netlify.app/docs/vcluster/next/manage/deploy-changes
Closes DOC-574
=> feat(migration): k3s->k8s migration guide

vcluster/deploy/upgrade/supported_versions.mdx
- Add v1.33 for table.  
[Link to Preview](https://deploy-preview-672--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/upgrade/supported_versions#kubernetes-compatibility-matrix)
Closes DOC-613
=> fix: update compatibility matrix with 1.33

vcluster/configure/vcluster-yaml/control-plane/components/distro/k8s.mdx
https://deploy-preview-677--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/distro/k8s
Closes DOC-601
=> feat: consolidated k8s disro image setting

.github/workflows/linear-pr-comments.yaml
This adds a simple automation whereby any reference to linear issue ID in a PR body will add a comment with the link to the linear issue.
Tested in this repo: https://github.com/LoftLabs-Experiments/linear-pr-comments
N/A
Closes OPS-160
=> feat: add pr comments with linear issue link

.github/workflows/linear-pr-comments.yaml
=> chore: exclude dependabot from ci triggers

src/components/InterpolatedCodeBlock/index.js, src/css/content/code.scss
When using the `InterpolatedCodeBlock` component the css changes visually connect dynamic variables and code.
Closes DOC-629
=> feat(style): visually connect dynamic variables and code

docusaurus.config.js
- Add the EOL to the nav for v21
[Link to Preview](https://deploy-preview-695--vcluster-docs-site.netlify.app/docs/vcluster)
Closes DOC-624
=> fix: add EOL to v21

netlify.toml
This adds a new permalink for the platform:
`/docs/platform-ui-link/platform/crd/ownedaccesskey` -> `/docs/platform/api/resources/ownedaccesskey`
=> feat: Add platform permalink for ownedaccesskeys

.github/styles/Loft/no-indented-admonitions-in-steps.yml
=> chore: vale rule to prevent admonitions indentaiton in Step tags

platform/configure/domain.mdx
There are 2 Encode CA Certificate sections where the base64 command has the -d flag so is decoding not encoding
Closes DOC-
=> correct base64 Encode CA certificate

platform/_partials/auth/sso/oidc.mdx
Added allowedExtraClaims to config along with description.
https://deploy-preview-710--vcluster-docs-site.netlify.app/docs/platform/next/configure/single-sign-on/providers/openid-connect
Closes DOC-532
=> Add allowed extra claims

platform/install/advanced/air-gapped.mdx, vcluster/configure/vcluster-yaml/sync/from-host/nodes.mdx, vcluster/configure/vcluster-yaml/sync/to-host/advanced/custom-resources.mdx, vcluster/learn-how-to/control-node-ip-visibility.mdx
This PR rebases on top of #698 which should be merged first.
Closes DOC-614
=> refactor(vcluster): move Gateway API and remove cert-manager examples

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/deploy.mdx, vcluster_versioned_docs/version-0.25.0/configure/vcluster-yaml/control-plane/components/backing-store/etcd/deploy.mdx
[Link to Preview](https://deploy-preview-712--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/backing-store/etcd/deploy#migration-options)
Closes ENG-5634
=> document how to perform and validate external -> embedded etcd migration

platform/administer/users-permissions/permissions/vcluster.mdx
-[Link to Preview](https://deploy-preview-715--vcluster-docs-site.netlify.app/docs/platform/next/administer/users-permissions/permissions/vcluster)
Closes DOC-617
=> fix: split permissions doc

platform/reference/glossary.mdx, scripts/generate-glossary-usage.js, src/data/glossary-usage.json, src/data/glossary.yaml, vcluster/reference/glossary.mdx
Glossary term can be referenced in platform only, vcluster only or both. The following syntaxt is supported.
```yaml
type: "platform"
type: ["platform", "vcluster"]
```
Closes DOC-655
=> feat: same glossary term can be referenced in platform and vcluster

README.md, package.json, scripts/wrap-glossary-terms.js
To automatically wrap glossary terms in MDX files with `<GlossaryTerm>` components:
```bash
npm run wrap-glossary vcluster/deploy/basics.mdx
npm run wrap-glossary vcluster/deploy/
node scripts/wrap-glossary-terms.js platform/understand/
```
The script will:
- Only wrap terms that exist in `src/data/glossary.yaml`
- Only wrap the first occurrence of each term in a document
- Respect the glossary type setting (vcluster, platform, or both)
- Skip terms in front matter, code blocks, links, and HTML/JSX tags
- Preserve the original case of matched terms
N/A
Closes DOC-658
=> feat: add glossary terms helper script

platform/_partials/auth/sso/oidc.mdx
https://deploy-preview-728--vcluster-docs-site.netlify.app/docs/platform/next/configure/single-sign-on/providers/openid-connect
Closes DOC-
=> Add when AllowedExtraClaims are applied to User

src/js/details-clicks.js, vcluster/_partials/admonitions/pro-admonition.mdx, vcluster_versioned_docs/version-0.20.0/_partials/admonitions/pro-admonition.mdx, vcluster_versioned_docs/version-0.21.0/_partials/admonitions/pro-admonition.mdx, vcluster_versioned_docs/version-0.22.0/_partials/admonitions/pro-admonition.mdx, vcluster_versioned_docs/version-0.23.0/_partials/admonitions/pro-admonition.mdx, vcluster_versioned_docs/version-0.24.0/_partials/admonitions/pro-admonition.mdx, vcluster_versioned_docs/version-0.25.0/_partials/admonitions/pro-admonition.mdx
- Fixed React warnings by changing `class` to `className` in pro-admonition.mdx partials across all versions to prevent errors like these:
- Removed infinite recursion in details-clicks.js that was causing "Too many calls to Location or History APIs" errors
- Added proper ExecutionEnvironment checks for browser-specific functions to prevent SSR issues
- Tested on production build and confirmed no regression errors
Browser errors like these should no longer appear when running `npm run start` on configuration pages with pro/enterprise labels.
https://deploy-preview-740--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/
Closes DOC-665
=> fix(infra): javascript calls overload in dev mode

vcluster/configure/vcluster-yaml/sync/to-host/core/pods/hybrid-scheduling.mdx
[Link to preview](https://deploy-preview-747--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/to-host/core/pods/hybrid-scheduling)
Closes DOC-675
=> fix: Small edits for clarity

platform/install/environments/gcp.mdx
- Updates to align with EKS docs
[Link to Preview](https://deploy-preview-765--vcluster-docs-site.netlify.app/docs/platform/next/install/environments/gcp)
Closes DOC-
=> fix: edits to align GCP docs

platform/api/_category_.json, platform/how-to/_category_.json, platform/reference/_category_.json, platform/troubleshoot/_category_.json, platform/troubleshoot/tsnet-connectivity.mdx
- Add troubleshooting section for platform (like what is in vCluster docs)
[Link to Preview](https://deploy-preview-721--vcluster-docs-site.netlify.app/docs/platform/next/troubleshoot/tsnet-connectivity)
Closes DOC-571
=> fix: add troubleshoot for tsnet connection

platform/configure/config.mdx, platform_versioned_docs/version-4.3.0/configure/config.mdx
- Just update for doc as follow up
Closes DOC-610
=> fix: Update and add docs to main for follow up for agent link

vcluster/_fragments/private-nodes.mdx
- Follow up to address vale rules
Closes DOC-673
Closes DOC-699
=> fix: Follow up for private node vale

netlify.toml
https://deploy-preview-781--next-vcluster-docs-site.netlify.app/docs/
Closes DOC-698
=> feat(dns): redirect next.vcluster.com directly to docs path

vcluster/learn-how-to/capture-pprof-vcluster.mdx
- Just a follow up to address vale issues
Closes DOC-663
=> Fix: Follow up to fix vale issues for capture-pprof-vcluster.mdx

vcluster/_fragments/private-nodes.mdx
=> remove mentiones of Cluster API as there aren't working yet

vcluster/introduction/architecture.mdx, vcluster_versioned_docs/version-0.25.0/introduction/architecture.mdx
Removed sentence that falsely states running multiple vCluster instances in the same host namespace is possible.
Closes DOC-
=> Since 0.25 it is not possible to have multiple vCluster instances in a single host namespace

platform/api/_partials/resources/config/external/platform/project.mdx, vcluster/configure/vcluster-yaml/external/platform/project.mdx
[Link to Preview](https://deploy-preview-817--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/external/platform/project)
Closes DOC-631
=> add docs for setting project for external vclusters

vcluster/configure/vcluster-yaml/sync/to-host/core/pods/hybrid-scheduling.mdx
- add pro admonition for hybrid scheduling
[Link to Preview](https://deploy-preview-825--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/to-host/core/pods/hybrid-scheduling)
Closes DOC-
=> fix: add pro

vcluster/_fragments/sync/class-syncing.mdx, vcluster/configure/vcluster-yaml/sync/from-host/ingress-classes.mdx, vcluster/configure/vcluster-yaml/sync/from-host/priority-classes.mdx, vcluster/configure/vcluster-yaml/sync/from-host/runtime-classes.mdx, vcluster/configure/vcluster-yaml/sync/from-host/storage-classes.mdx
Replacing #748 
This PR includes docs for the new limiting feature for :
- `ingressClasses`
- `storageClasses`
- `runtimeClasses`
- `priorityClasses`
https://deploy-preview-828--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/from-host/ingress-classes
https://deploy-preview-828--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/from-host/priority-classes
https://deploy-preview-828--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/from-host/runtime-classes
https://deploy-preview-828--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/from-host/storage-classes
Closes DOC-586
=> feature: Add `sync.fromHost.*Classes` limits

vcluster/deploy/upgrade/supported_versions.mdx
Updates compatibility matrix for k8s 1.33 to `Officially tested and supported`
Closes ENG-6637
=> update compatibility matrix for 1.33

platform/administer/backup-restore/backup-restore-platform.mdx
Clarifies that the platform backup covers only CRDs and does not include other resources used by the platform deployment or connected clusters.
[Document Preview](https://deploy-preview-841--vcluster-docs-site.netlify.app/docs/platform/next/administer/backup-restore/backup-restore-platform)
Closes DOC-735
=> docs(platform): clarify backup scope

vcluster/learn-how-to/override-alpine-sidecar.mdx
https://linear.app/loft/issue/ENG-6381/vcluster-should-provide-alpine-linux-image-from-ghcr-or-another-public
[Link to Preview](https://deploy-preview-839--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/override-alpine-sidecar)
References ENG-6381
DOC-756
=> fix: Update about when users get rate limited by docker hub

src/theme/DocSidebarItem/Category/index.tsx
Menu navigation has a known limitation, after navigating to a category and collapsing it, clicking the category again won't expand it (only navigates). Workaround: Click elsewhere first, then click the category.
To test, click on every nested menu category and see if it behaves as expected.
https://deploy-preview-855--vcluster-docs-site.netlify.app/docs/vcluster/configure/vcluster-yaml/
Closes DOC-763
=> fix: multi level menu nativation

docusaurus.config.js, static/robots.txt
- Add 301 redirects for EOL v0.19 docs to latest version
- Create robots.txt to block search crawling of EOL versions 
- Add noIndex to EOL versions (0.20-0.22)
- Add canonical URL metadata for better SEO
https://deploy-preview-859--vcluster-docs-site.netlify.app/docs/
References DOC-789
=> feat: redirect seo and search traffic to new docs

platform/install/advanced/air-gapped.mdx, vcluster/deploy/topologies/air-gapped.mdx
- Remove references of the old image `loft-image.tXt`
[Link to Preview](https://deploy-preview-860--vcluster-docs-site.netlify.app/docs/platform/next/install/advanced/air-gapped)
Closes DOC-790
=> fix: update air-gap docs to include `images.txt`

docusaurus.config.js, static/robots.txt
We want to keep indexing old docs versions, not to lose SEO. Since `docusaurus` generates [automatically canonical links](https://docusaurus.io/docs/seo#single-page-metadata) for every page, we do not need to specify additional configuration.
https://deploy-preview-862--vcluster-docs-site.netlify.app/docs/
References DOC-789
=> fix: old docs versions should be indexed

docusaurus.config.js, package-lock.json, package.json, static/robots.txt
Adding [sitemap plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap) for better search engine indexing. Each page has its own canonical link generated. Added config for dynamic priorities based on content type.
- Guide search engines to prioritize important content
- Downrank EOL versions while keeping them indexed
- **Priorities**: Home (1.0) → Current (stable) versions (0.9) → All other versions (0.3)
- **Changefreq**: Daily for home, weekly for active docs, older versions
- verify that the sitemap is there `curl -s https://deploy-preview-863--vcluster-docs-site.netlify.app/docs/sitemap.xml | head -100`
- and has correct priorities and frequencies (spot checks)
- verify docs work as expected (spot checks)
https://deploy-preview-863--vcluster-docs-site.netlify.app/do …
=> feat: add sitemap for better search engine crawling results

vcluster/learn-how-to/configure-kai-scheduler.mdx
https://deploy-preview-858--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/configure-kai-scheduler
Closes DOC-787
=> fix: kai scheduler commands and flow

vcluster/learn-how-to/configure-kai-scheduler.mdx
https://deploy-preview-865--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/configure-kai-scheduler
Closes DOC-787
=> fix(kai-scheduler): add enterprise admonition

scripts/wrap-glossary-terms.js, src/data/glossary.yaml, vcluster/configure/vcluster-yaml/control-plane/components/distro/k8s.mdx
- tested locally on KIND cluster
- minor fix in the `glossary-wrapper` to prevent tags wrapping in import paths and markdown headers
- extending glossary with related terms
https://deploy-preview-868--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/control-plane/components/distro/k8s#api-server-rate-limiting
Closes DOC-765
=> feat: add rate limiting configuration

vcluster/deploy/environment/eks.mdx, vcluster_versioned_docs/version-0.22.0/deploy/environment/eks.mdx, vcluster_versioned_docs/version-0.23.0/deploy/environment/eks.mdx, vcluster_versioned_docs/version-0.24.0/deploy/environment/eks.mdx, vcluster_versioned_docs/version-0.25.0/deploy/environment/eks.mdx, vcluster_versioned_docs/version-0.26.0/deploy/environment/eks.mdx
- fixes indentation issues when YAML snippets are wrapped in bash here docs
- the InterpolatedCodeBlock component works correctly, however it needs string literals in the above case
- further adjustments to the component planned to improve tech writer's design time flow
- test the YAML commands for correctness
- ensure no regression bugs were introduced
- confirm older versions are correct as well
https://deploy-preview-870--vcluster-docs-site.netlify.app/docs/vcluster/next/deploy/environment/eks
Closes DOC-800
=> fix: yaml indentation in the eks cluster creation examples

vcluster/integrations/pod-identity/aks-workload-identity.mdx
Added a new documentation page for the Azure AKS Workload Identity integration
[Document Preview](https://deploy-preview-856--vcluster-docs-site.netlify.app/docs/vcluster/next/integrations/pod-identity/aks-workload-identity).
Closes DOC-662
=> feat: AKS workload identity integration

vcluster/configure/vcluster-yaml/control-plane/components/backing-store/etcd/embedded.mdx
Add an upgrade warning for the embedded etcd feature.
Closes ENG-6982
=> Add warning for embedded etcd upgrade to 3.6

platform/configure/config.mdx
[Document Preview](https://deploy-preview-887--vcluster-docs-site.netlify.app/docs/platform/next/configure/config#retrieve-agent-values)
Closes DOC-731
=> document agent-values endpoint

vcluster/manage/certificates.mdx
=> chore: remove backslash and link in cert rotation docs

vcluster/manage/certificates.mdx
=> fix: add note that the virtual cluster must be in running state

vcluster/troubleshoot/kubectl-port-forward-ingress-issues.mdx
Add troubleshooting guide for kubectl port-forward connection upgrade errors with Ingress
[Document Preview](https://deploy-preview-937--vcluster-docs-site.netlify.app/docs/vcluster/next/troubleshoot/kubectl-port-forward-ingress-issues/)
Closes DOC-825
=> feat: add kubectl port-forward troubleshooting page

vcluster/manage/certificates.mdx
https://deploy-preview-882--next-vcluster-docs-site.netlify.app/docs/vcluster/next/manage/certificates
Closes DOC-808
=> Certificates private nodes

vcluster/configure/vcluster-yaml/sync/to-host/core/pods/README.mdx
Fixes flow by adding a section, so the previously added note has some context.
Closes ENG-7954
=> Add section for sync.toHost.rewriteHosts

vcluster/_fragments/integrations/cert-manager.mdx, vcluster/configure/vcluster-yaml/sync/from-host/configmaps.mdx, vcluster/configure/vcluster-yaml/sync/from-host/custom-resources.mdx, vcluster/configure/vcluster-yaml/sync/from-host/secrets.mdx, vcluster/configure/vcluster-yaml/sync/to-host/advanced/custom-resources.mdx
- Rewrite for cert-manager docs  for July improvements
Closes DOC-755
=> refactor: Rewrite cert-manager docs

vcluster/_fragments/eso.mdx
Warn about the latest version that is compatible with vCluster integration
Closes DOC-
=> Warn about the latest version that is compatible with vCluster integration

vcluster/configure/vcluster-yaml/sync/to-host/advanced/namespaces.mdx
Adds `Known limitations` section to `sync.toHost.namespaces` docs
https://deploy-preview-955--vcluster-docs-site.netlify.app/docs/vcluster/next/configure/vcluster-yaml/sync/to-host/advanced/namespaces
Closes DOC-754
=> Add known limitations section to namespace sync docs

netlify.toml
=> fix(infra): bump node version on netlify and add memory logs

docusaurus.config.js
This helps reduce memory build footprint and pass netlify builds.
References DOC-897
=> fix(infra): exclude 3 EOL versions from the build settings

docusaurus.config.js, src/theme/DocSidebar/Desktop/Content/index.js
=> chore(infra): redirect old docs to a dedicated standalone versions

platform/install/advanced/air-gapped.mdx
Adds a new section to the airgapped docs explaining `config.uiSettings.externalURLs` to restrict what the platform UI can access
Closes DOC-594
=> docs(platform): add section to explain externalURLs for airgapped deployments

platform/understand/what-are-templates.mdx, platform_versioned_docs/version-4.2.0/understand/what-are-templates.mdx, platform_versioned_docs/version-4.3.0/understand/what-are-templates.mdx
https://deploy-preview-1054--vcluster-docs-site.netlify.app/docs/platform/understand/what-are-templates
Closes DOC-902
=> fix(platform): remove recursive link in allowed templates

platform/index.mdx, platform_versioned_docs/version-4.2.0/index.mdx, platform_versioned_docs/version-4.3.0/index.mdx
=> fix(infra): safari renders diagrams incorreclty with htmlLabels

vcluster/_fragments/eso.mdx
Add version to ESO integration
Implementation:
OSS -> https://github.com/loft-sh/vcluster/pull/3118
PRO -> https://github.com/loft-sh/vcluster-pro/pull/1065
[Document Preview](https://deploy-preview-1053--vcluster-docs-site.netlify.app/docs)
=> Add version to ESO integration

src/theme/DocSidebar/Desktop/Content/index.js
=> chore(vcluster): mark 0.23 as EOL

vcluster/troubleshoot/noexec-emptydir-volumes.mdx
https://deploy-preview-1020--vcluster-docs-site.netlify.app/docs/vcluster/next/troubleshoot/noexec-emptydir-volumes
Closes DOC-788
=> feat(vcluster): troubleshooting guide for noexec emptyDir volumes

vcluster/configure/vcluster-yaml/sync/to-host/core/pods/hybrid-scheduling.mdx, vcluster/learn-how-to/control-plane/container/use-custom-schedulers.mdx
Add guide that shows how to deploy custom schedulers in both host and virtual cluster, and then use both of them in a virtual cluster, by enabling Hybrid Scheduling.
[Custom schedulers with Hybrid scheduling example preview](https://deploy-preview-1076--vcluster-docs-site.netlify.app/docs/vcluster/next/learn-how-to/control-plane/container/use-custom-schedulers)
Closes DOC-725
=> Add custom schedulers example

.github/workflows/sync-next-branch.yml, hack/sync-branches.sh
=> feat(ci): rebase main onto next istead of merging to avoid conflicts

.github/workflows/sync-next-branch.yml, hack/sync-branches.sh
Correctly preserve all commits from both branches
Closes DOC-
=> fix(ci): sync main with next

vcluster/_fragments/patches.mdx
This reverts commit 47c30bd1e5036ff74d9667cc59efbe4146492814.
Closes ENG-8793
@netlify /docs
=> Revert "feature(patches): Docs on adding new values to maps. (#945)"

src/css/sidebar.scss
https://deploy-preview-1108--vcluster-docs-site.netlify.app/docs/vcluster/deploy/worker-nodes/private-nodes/
Closes DOC-864
@netlify /docs
=> refactor(layout): add some padding between enterprise label and chevron

platform/administer/node-providers/kubevirt.mdx
Enhancement of KubeVirt VM example. For auto nodes users should use the bridge mode.
Otherwise all created guests will have the same IP address.
Closes DOC-
@netlify /docs
=> fix: use the default bridge mode for the KubeVirt auto-nodes example

.vale.ini
Vale `BlockIgnore` must be on separate lines.
Closes DOC-
@netlify /docs
=> fix(vale): blockignore should be on separate lines

vcluster/configure/vcluster-yaml/external/platform/api-key.mdx, vcluster_versioned_docs/version-0.24.0/configure/vcluster-yaml/external/platform/api-key.mdx, vcluster_versioned_docs/version-0.25.0/configure/vcluster-yaml/external/platform/api-key.mdx, vcluster_versioned_docs/version-0.26.0/configure/vcluster-yaml/external/platform/api-key.mdx, vcluster_versioned_docs/version-0.27.0/configure/vcluster-yaml/external/platform/api-key.mdx
=> fix: use empty object for dedicated access key

platform/administer/clusters/advanced/agent-config.mdx, platform/configure/config.mdx
This was locally tested 
- Kubernetes cluster: `v1.30.13`
- vCluster Platform: `v4.3.5`
- Verified annotation storage and format with `kubectl get cluster test-security-cluster -o yaml`
- Confirmed precedence order: cluster annotation → platform agentValues → platform defaults
- Tested helm template generation with security context values to verify field application
- Inspected running platform deployment to confirm actual security context usage
https://deploy-preview-1098--vcluster-docs-site.netlify.app/docs/platform/next/administer/clusters/advanced/agent-config
https://deploy-preview-1098--vcluster-docs-site.netlify.app/docs/platform/next/administer/clusters/advanced/agent-config
Closes DOC-898
=> feat(vcluster): security context integration

.github/styles/Loft/kubernetes-api-kinds.yml
Testing strategy:
-  API kinds with backticks - Should trigger warnings (e.g., StatefulSet)
-  API kinds without backticks - Should NOT trigger warnings (e.g., StatefulSet)
- possessive forms - Should work correctly (StatefulSet's = OK, StatefulSet's = warning)
-  triple backtick code blocks - Should be ignored completely
-  inline code - Commands like kubectl get pods should be ignored
-  both K8s and Platform CRDs - Verified both standard and vCluster-specific types
https://deploy-preview-1158--vcluster-docs-site.netlify.app/docs
Closes DOC-956
@netlify /docs
=> feat(vale): add rule warning about not wrapping kubernetes resources in backticks

docusaurus.config.js
=> chore: mark 0.24 as EOL in its branch

vcluster_versioned_docs/version-0.29.0/manage/certificates.mdx
Part of ENG-8077
Closes DOC-
@netlify /docs
=> Adds workaround to cert-rotation standalone, only in 0.29 docs

platform/use-platform/virtual-clusters/key-features/snapshots.mdx, platform_versioned_docs/version-4.4.0/use-platform/virtual-clusters/key-features/snapshots.mdx
https://deploy-preview-1200--vcluster-docs-site.netlify.app/docs/platform/next/use-platform/virtual-clusters/key-features/snapshots
Closes DOC-985
@netlify /docs
=> fix(platform): invalid semantic snapshot type in examples
